name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER)'
version-template: '$MAJOR.$MINOR.$PATCH'
categories:
  - title: 'Fonctionnalites'
    labels:
      - feature
      - enhancement
  - title: 'Securite'
    labels:
      - security
  - title: 'Qualite'
    labels:
      - tests
      - ci
  - title: 'Maintenance'
    labels:
      - chore
      - dependencies
change-title-escapes: '\\<*_&'
template: |
  ## Changements

  $CHANGES
