<?php
declare(strict_types=1);

$keys = [
    'propose_ad',
    'propose_category',
    'propose_category_subject',
    'propose_category_intro',
    'propose_category_email_intro',
    'propose_category_name_label',
    'propose_category_name_placeholder',
    'propose_category_sender_name_label',
    'propose_category_sender_email_label',
    'propose_category_details_label',
    'propose_category_details_placeholder',
    'propose_category_submit',
    'propose_category_cancel',
    'propose_category_close',
    'propose_category_invalid',
    'propose_category_sent',
    'propose_category_failed',
];

$rows = <<<'ROWS'
fr|Proposer une annonce|Proposer une catégorie|Proposition de catégorie pour les petites annonces ON4CRD|Décrivez la catégorie souhaitée. Le club la validera avant de l'ajouter aux petites annonces.|Nouvelle proposition de catégorie pour les petites annonces ON4CRD.|Nom de la catégorie|Ex. Antennes, accessoires, composants|Votre nom|Votre e-mail|Détails / justification|Expliquez le type d'annonces concernées ou l'intérêt de cette catégorie.|Envoyer la proposition|Annuler|Fermer|Veuillez compléter correctement le formulaire de proposition.|Proposition de catégorie envoyée.|La proposition n'a pas pu être envoyée. Réessayez plus tard.
en|Propose an ad|Propose a category|Category proposal for ON4CRD classifieds|Describe the category you would like. The club will review it before adding it to classifieds.|New category proposal for ON4CRD classifieds.|Category name|E.g. antennas, accessories, components|Your name|Your email|Details / reason|Explain what type of ads are involved or why this category is useful.|Send proposal|Cancel|Close|Please complete the proposal form correctly.|Category proposal sent.|The proposal could not be sent. Try again later.
de|Eine Anzeige vorschlagen|Kategorie vorschlagen|Kategorievorschlag für die ON4CRD-Kleinanzeigen|Beschreiben Sie die gewünschte Kategorie. Der Club prüft sie, bevor sie zu den Kleinanzeigen hinzugefügt wird.|Neuer Kategorievorschlag für die ON4CRD-Kleinanzeigen.|Name der Kategorie|Z. B. Antennen, Zubehör, Bauteile|Ihr Name|Ihre E-Mail|Details / Begründung|Erklären Sie, welche Art von Anzeigen betroffen ist oder warum diese Kategorie nützlich ist.|Vorschlag senden|Abbrechen|Schließen|Bitte füllen Sie das Vorschlagsformular korrekt aus.|Kategorievorschlag gesendet.|Der Vorschlag konnte nicht gesendet werden. Versuchen Sie es später erneut.
nl|Een advertentie voorstellen|Een categorie voorstellen|Categorievoorstel voor de ON4CRD-advertenties|Beschrijf de gewenste categorie. De club beoordeelt ze voordat ze aan de advertenties wordt toegevoegd.|Nieuw categorievoorstel voor de ON4CRD-advertenties.|Naam van de categorie|Bijv. antennes, accessoires, onderdelen|Uw naam|Uw e-mail|Details / motivatie|Leg uit welk type advertenties bedoeld is of waarom deze categorie nuttig is.|Voorstel verzenden|Annuleren|Sluiten|Vul het voorstelformulier correct in.|Categorievoorstel verzonden.|Het voorstel kon niet worden verzonden. Probeer later opnieuw.
it|Proporre un annuncio|Proporre una categoria|Proposta di categoria per gli annunci ON4CRD|Descrivi la categoria desiderata. Il club la valuterà prima di aggiungerla agli annunci.|Nuova proposta di categoria per gli annunci ON4CRD.|Nome della categoria|Es. antenne, accessori, componenti|Il tuo nome|La tua e-mail|Dettagli / motivazione|Spiega il tipo di annunci interessati o l'utilità di questa categoria.|Invia la proposta|Annulla|Chiudi|Compila correttamente il modulo di proposta.|Proposta di categoria inviata.|Impossibile inviare la proposta. Riprova più tardi.
es|Proponer un anuncio|Proponer una categoría|Propuesta de categoría para los clasificados ON4CRD|Describe la categoría deseada. El club la revisará antes de añadirla a los clasificados.|Nueva propuesta de categoría para los clasificados ON4CRD.|Nombre de la categoría|Ej. antenas, accesorios, componentes|Tu nombre|Tu correo electrónico|Detalles / justificación|Explica el tipo de anuncios afectados o la utilidad de esta categoría.|Enviar la propuesta|Cancelar|Cerrar|Completa correctamente el formulario de propuesta.|Propuesta de categoría enviada.|No se pudo enviar la propuesta. Inténtalo más tarde.
pt|Propor um anúncio|Propor uma categoria|Proposta de categoria para os classificados ON4CRD|Descreva a categoria pretendida. O clube irá validá-la antes de a adicionar aos classificados.|Nova proposta de categoria para os classificados ON4CRD.|Nome da categoria|Ex. antenas, acessórios, componentes|O seu nome|O seu e-mail|Detalhes / justificação|Explique o tipo de anúncios abrangidos ou a utilidade desta categoria.|Enviar proposta|Cancelar|Fechar|Preencha corretamente o formulário de proposta.|Proposta de categoria enviada.|Não foi possível enviar a proposta. Tente novamente mais tarde.
bg|Предложете обява|Предложете категория|Предложение за категория за малките обяви на ON4CRD|Опишете желаната категория. Клубът ще я прегледа, преди да я добави към малките обяви.|Ново предложение за категория за малките обяви на ON4CRD.|Име на категорията|Напр. антени, аксесоари, компоненти|Вашето име|Вашият e-mail|Подробности / обосновка|Обяснете какъв тип обяви ще включва или защо е полезна.|Изпрати предложението|Отказ|Затвори|Моля, попълнете правилно формуляра.|Предложението за категория е изпратено.|Предложението не можа да бъде изпратено. Опитайте по-късно.
hr|Predloži oglas|Predloži kategoriju|Prijedlog kategorije za ON4CRD male oglase|Opišite željenu kategoriju. Klub će je provjeriti prije dodavanja u male oglase.|Novi prijedlog kategorije za ON4CRD male oglase.|Naziv kategorije|Npr. antene, dodatna oprema, komponente|Vaše ime|Vaš e-mail|Detalji / obrazloženje|Objasnite koju vrstu oglasa obuhvaća ili zašto je korisna.|Pošalji prijedlog|Odustani|Zatvori|Ispravno ispunite obrazac prijedloga.|Prijedlog kategorije poslan.|Prijedlog nije bilo moguće poslati. Pokušajte kasnije.
cs|Navrhnout inzerát|Navrhnout kategorii|Návrh kategorie pro inzerci ON4CRD|Popište požadovanou kategorii. Klub ji před přidáním do inzerce zkontroluje.|Nový návrh kategorie pro inzerci ON4CRD.|Název kategorie|Např. antény, příslušenství, součástky|Vaše jméno|Váš e-mail|Detaily / zdůvodnění|Vysvětlete, jaký typ inzerátů zahrnuje nebo proč je užitečná.|Odeslat návrh|Zrušit|Zavřít|Vyplňte prosím formulář správně.|Návrh kategorie odeslán.|Návrh se nepodařilo odeslat. Zkuste to později.
da|Foreslå en annonce|Foreslå en kategori|Kategoriforslag til ON4CRD-annoncer|Beskriv den ønskede kategori. Klubben gennemgår den, før den tilføjes til annoncerne.|Nyt kategoriforslag til ON4CRD-annoncer.|Kategorinavn|F.eks. antenner, tilbehør, komponenter|Dit navn|Din e-mail|Detaljer / begrundelse|Forklar hvilken type annoncer den gælder, eller hvorfor kategorien er nyttig.|Send forslag|Annuller|Luk|Udfyld formularen korrekt.|Kategoriforslag sendt.|Forslaget kunne ikke sendes. Prøv igen senere.
et|Paku kuulutus|Paku kategooria|Kategooria ettepanek ON4CRD kuulutustele|Kirjeldage soovitud kategooriat. Klubi vaatab selle üle enne kuulutustesse lisamist.|Uus kategooria ettepanek ON4CRD kuulutustele.|Kategooria nimi|Nt antennid, tarvikud, komponendid|Teie nimi|Teie e-post|Üksikasjad / põhjendus|Selgitage, millist tüüpi kuulutusi see hõlmab või miks see kasulik on.|Saada ettepanek|Tühista|Sule|Palun täitke ettepaneku vorm õigesti.|Kategooria ettepanek saadetud.|Ettepanekut ei saanud saata. Proovige hiljem uuesti.
fi|Ehdota ilmoitusta|Ehdota kategoriaa|Kategoriaehdotus ON4CRD:n ilmoituksille|Kuvaile haluttu kategoria. Kerho tarkistaa sen ennen lisäämistä ilmoituksiin.|Uusi kategoriaehdotus ON4CRD:n ilmoituksille.|Kategorian nimi|Esim. antennit, tarvikkeet, komponentit|Nimesi|Sähköpostisi|Tiedot / perustelu|Kerro, minkä tyyppisiä ilmoituksia se koskee tai miksi kategoria on hyödyllinen.|Lähetä ehdotus|Peruuta|Sulje|Täytä ehdotuslomake oikein.|Kategoriaehdotus lähetetty.|Ehdotusta ei voitu lähettää. Yritä myöhemmin uudelleen.
el|Προτείνετε μια αγγελία|Προτείνετε μια κατηγορία|Πρόταση κατηγορίας για τις αγγελίες ON4CRD|Περιγράψτε την επιθυμητή κατηγορία. Ο σύλλογος θα την ελέγξει πριν την προσθέσει στις αγγελίες.|Νέα πρόταση κατηγορίας για τις αγγελίες ON4CRD.|Όνομα κατηγορίας|Π.χ. κεραίες, αξεσουάρ, εξαρτήματα|Το όνομά σας|Το e-mail σας|Λεπτομέρειες / αιτιολόγηση|Εξηγήστε ποιον τύπο αγγελιών αφορά ή γιατί είναι χρήσιμη.|Αποστολή πρότασης|Ακύρωση|Κλείσιμο|Συμπληρώστε σωστά τη φόρμα πρότασης.|Η πρόταση κατηγορίας στάλθηκε.|Δεν ήταν δυνατή η αποστολή της πρότασης. Δοκιμάστε ξανά αργότερα.
hu|Hirdetés javaslata|Kategória javaslata|Kategóriajavaslat az ON4CRD apróhirdetésekhez|Írja le a kívánt kategóriát. A klub ellenőrzi, mielőtt hozzáadja az apróhirdetésekhez.|Új kategóriajavaslat az ON4CRD apróhirdetésekhez.|Kategória neve|Pl. antennák, tartozékok, alkatrészek|Az Ön neve|Az Ön e-mail címe|Részletek / indoklás|Magyarázza el, milyen hirdetésekre vonatkozik vagy miért hasznos.|Javaslat elküldése|Mégse|Bezárás|Kérjük, töltse ki helyesen a javaslati űrlapot.|Kategóriajavaslat elküldve.|A javaslatot nem sikerült elküldeni. Próbálja újra később.
ga|Mol fógra|Mol catagóir|Moladh catagóire do na fógraí beaga ON4CRD|Déan cur síos ar an gcatagóir atá uait. Déanfaidh an club athbhreithniú uirthi sula gcuirfear leis na fógraí í.|Moladh catagóire nua do na fógraí beaga ON4CRD.|Ainm na catagóire|M.sh. aeróga, gabhálais, comhpháirteanna|D'ainm|Do ríomhphost|Sonraí / cúis|Mínigh cén cineál fógraí atá i gceist nó cén fáth a bhfuil sí úsáideach.|Seol an moladh|Cealaigh|Dún|Líon an fhoirm mholta i gceart, le do thoil.|Seoladh an moladh catagóire.|Níorbh fhéidir an moladh a sheoladh. Bain triail eile as níos déanaí.
lv|Ierosināt sludinājumu|Ierosināt kategoriju|Kategorijas priekšlikums ON4CRD sludinājumiem|Aprakstiet vēlamo kategoriju. Klubs to pārbaudīs pirms pievienošanas sludinājumiem.|Jauns kategorijas priekšlikums ON4CRD sludinājumiem.|Kategorijas nosaukums|Piem., antenas, piederumi, komponenti|Jūsu vārds|Jūsu e-pasts|Detaļas / pamatojums|Paskaidrojiet, kāda veida sludinājumiem tā paredzēta vai kāpēc tā ir noderīga.|Nosūtīt priekšlikumu|Atcelt|Aizvērt|Lūdzu, pareizi aizpildiet priekšlikuma veidlapu.|Kategorijas priekšlikums nosūtīts.|Priekšlikumu neizdevās nosūtīt. Mēģiniet vēlāk.
lt|Pasiūlyti skelbimą|Pasiūlyti kategoriją|Kategorijos pasiūlymas ON4CRD skelbimams|Aprašykite norimą kategoriją. Klubas ją peržiūrės prieš pridėdamas prie skelbimų.|Naujas kategorijos pasiūlymas ON4CRD skelbimams.|Kategorijos pavadinimas|Pvz., antenos, priedai, komponentai|Jūsų vardas|Jūsų el. paštas|Išsami informacija / pagrindimas|Paaiškinkite, kokio tipo skelbimams ji skirta arba kodėl naudinga.|Siųsti pasiūlymą|Atšaukti|Uždaryti|Teisingai užpildykite pasiūlymo formą.|Kategorijos pasiūlymas išsiųstas.|Pasiūlymo nepavyko išsiųsti. Bandykite vėliau.
mt|Ipproponi reklam|Ipproponi kategorija|Proposta ta’ kategorija għar-reklami żgħar ON4CRD|Iddeskrivi l-kategorija mixtieqa. Il-klabb jirrevediha qabel iżidha mar-reklami żgħar.|Proposta ġdida ta’ kategorija għar-reklami żgħar ON4CRD.|Isem il-kategorija|Eż. antenni, aċċessorji, komponenti|Ismek|L-e-mail tiegħek|Dettalji / ġustifikazzjoni|Spjega x’tip ta’ reklami tkopri jew għaliex hija utli.|Ibgħat il-proposta|Ikkanċella|Agħlaq|Jekk jogħġbok imla l-formola tal-proposta b’mod korrett.|Il-proposta tal-kategorija ntbagħtet.|Il-proposta ma setgħetx tintbagħat. Erġa’ pprova aktar tard.
pl|Zaproponuj ogłoszenie|Zaproponuj kategorię|Propozycja kategorii dla ogłoszeń ON4CRD|Opisz potrzebną kategorię. Klub sprawdzi ją przed dodaniem do ogłoszeń.|Nowa propozycja kategorii dla ogłoszeń ON4CRD.|Nazwa kategorii|Np. anteny, akcesoria, komponenty|Twoje imię i nazwisko|Twój e-mail|Szczegóły / uzasadnienie|Wyjaśnij, jakiego typu ogłoszeń dotyczy lub dlaczego jest przydatna.|Wyślij propozycję|Anuluj|Zamknij|Wypełnij poprawnie formularz propozycji.|Propozycja kategorii wysłana.|Nie udało się wysłać propozycji. Spróbuj później.
ro|Propune un anunț|Propune o categorie|Propunere de categorie pentru anunțurile ON4CRD|Descrieți categoria dorită. Clubul o va verifica înainte de a o adăuga la anunțuri.|Propunere nouă de categorie pentru anunțurile ON4CRD.|Numele categoriei|Ex. antene, accesorii, componente|Numele dvs.|E-mailul dvs.|Detalii / justificare|Explicați ce tip de anunțuri vizează sau de ce este utilă.|Trimite propunerea|Anulează|Închide|Completați corect formularul de propunere.|Propunerea de categorie a fost trimisă.|Propunerea nu a putut fi trimisă. Încercați mai târziu.
sk|Navrhnúť inzerát|Navrhnúť kategóriu|Návrh kategórie pre inzeráty ON4CRD|Opíšte požadovanú kategóriu. Klub ju pred pridaním do inzerátov skontroluje.|Nový návrh kategórie pre inzeráty ON4CRD.|Názov kategórie|Napr. antény, príslušenstvo, súčiastky|Vaše meno|Váš e-mail|Podrobnosti / zdôvodnenie|Vysvetlite, aký typ inzerátov zahŕňa alebo prečo je užitočná.|Odoslať návrh|Zrušiť|Zavrieť|Vyplňte prosím formulár správne.|Návrh kategórie odoslaný.|Návrh sa nepodarilo odoslať. Skúste to neskôr.
sl|Predlagaj oglas|Predlagaj kategorijo|Predlog kategorije za male oglase ON4CRD|Opišite želeno kategorijo. Klub jo bo pregledal, preden jo doda med oglase.|Nov predlog kategorije za male oglase ON4CRD.|Ime kategorije|Npr. antene, dodatki, komponente|Vaše ime|Vaš e-mail|Podrobnosti / utemeljitev|Pojasnite, katero vrsto oglasov zajema ali zakaj je koristna.|Pošlji predlog|Prekliči|Zapri|Pravilno izpolnite obrazec za predlog.|Predlog kategorije poslan.|Predloga ni bilo mogoče poslati. Poskusite pozneje.
sv|Föreslå en annons|Föreslå en kategori|Kategoriförslag för ON4CRD-annonser|Beskriv önskad kategori. Klubben granskar den innan den läggs till i annonserna.|Nytt kategoriförslag för ON4CRD-annonser.|Kategorinamn|T.ex. antenner, tillbehör, komponenter|Ditt namn|Din e-post|Detaljer / motivering|Förklara vilken typ av annonser den gäller eller varför den är användbar.|Skicka förslag|Avbryt|Stäng|Fyll i förslagsformuläret korrekt.|Kategoriförslag skickat.|Förslaget kunde inte skickas. Försök igen senare.
ar|اقتراح إعلان|اقتراح فئة|اقتراح فئة لإعلانات ON4CRD الصغيرة|صف الفئة المطلوبة. سيقوم النادي بمراجعتها قبل إضافتها إلى الإعلانات الصغيرة.|اقتراح فئة جديد لإعلانات ON4CRD الصغيرة.|اسم الفئة|مثال: هوائيات، ملحقات، مكونات|اسمك|بريدك الإلكتروني|التفاصيل / المبرر|اشرح نوع الإعلانات المعنية أو سبب فائدة هذه الفئة.|إرسال الاقتراح|إلغاء|إغلاق|يرجى إكمال نموذج الاقتراح بشكل صحيح.|تم إرسال اقتراح الفئة.|تعذر إرسال الاقتراح. حاول مرة أخرى لاحقًا.
hi|विज्ञापन प्रस्तावित करें|श्रेणी प्रस्तावित करें|ON4CRD छोटी घोषणाओं के लिए श्रेणी प्रस्ताव|इच्छित श्रेणी का वर्णन करें। क्लब इसे छोटी घोषणाओं में जोड़ने से पहले समीक्षा करेगा।|ON4CRD छोटी घोषणाओं के लिए नया श्रेणी प्रस्ताव।|श्रेणी का नाम|उदाहरण: एंटेना, सहायक उपकरण, घटक|आपका नाम|आपका ईमेल|विवरण / कारण|बताएं कि यह किस प्रकार के विज्ञापनों के लिए है या यह क्यों उपयोगी है।|प्रस्ताव भेजें|रद्द करें|बंद करें|कृपया प्रस्ताव फ़ॉर्म सही ढंग से पूरा करें।|श्रेणी प्रस्ताव भेजा गया।|प्रस्ताव भेजा नहीं जा सका। बाद में फिर प्रयास करें।
ja|広告を提案する|カテゴリーを提案する|ON4CRDクラシファイドのカテゴリー提案|希望するカテゴリーを説明してください。クラブが確認してからクラシファイドに追加します。|ON4CRDクラシファイドへの新しいカテゴリー提案。|カテゴリー名|例: アンテナ、アクセサリー、部品|お名前|メールアドレス|詳細 / 理由|対象となる広告の種類や、このカテゴリーが有用な理由を説明してください。|提案を送信|キャンセル|閉じる|提案フォームを正しく入力してください。|カテゴリー提案を送信しました。|提案を送信できませんでした。後でもう一度お試しください。
zh|提议一个广告|提议一个类别|ON4CRD 分类广告类别提议|请描述所需类别。俱乐部会审核后再添加到分类广告中。|ON4CRD 分类广告的新类别提议。|类别名称|例如：天线、配件、组件|您的姓名|您的电子邮箱|详情 / 理由|说明涉及的广告类型或该类别的用途。|发送提议|取消|关闭|请正确填写提议表单。|类别提议已发送。|无法发送提议。请稍后再试。
bn|একটি বিজ্ঞাপন প্রস্তাব করুন|একটি বিভাগ প্রস্তাব করুন|ON4CRD ছোট বিজ্ঞাপনের জন্য বিভাগ প্রস্তাব|কাঙ্ক্ষিত বিভাগটি বর্ণনা করুন। ক্লাব এটি ছোট বিজ্ঞাপনে যোগ করার আগে পর্যালোচনা করবে।|ON4CRD ছোট বিজ্ঞাপনের জন্য নতুন বিভাগ প্রস্তাব।|বিভাগের নাম|যেমন: অ্যান্টেনা, আনুষঙ্গিক, উপাদান|আপনার নাম|আপনার ইমেল|বিস্তারিত / যুক্তি|কোন ধরনের বিজ্ঞাপনের জন্য বা কেন এটি উপকারী তা ব্যাখ্যা করুন।|প্রস্তাব পাঠান|বাতিল|বন্ধ করুন|অনুগ্রহ করে প্রস্তাব ফর্মটি সঠিকভাবে পূরণ করুন।|বিভাগ প্রস্তাব পাঠানো হয়েছে।|প্রস্তাব পাঠানো যায়নি। পরে আবার চেষ্টা করুন।
ru|Предложить объявление|Предложить категорию|Предложение категории для объявлений ON4CRD|Опишите желаемую категорию. Клуб проверит ее перед добавлением в объявления.|Новое предложение категории для объявлений ON4CRD.|Название категории|Например: антенны, аксессуары, компоненты|Ваше имя|Ваш e-mail|Подробности / обоснование|Объясните, для какого типа объявлений она нужна или чем полезна.|Отправить предложение|Отмена|Закрыть|Пожалуйста, корректно заполните форму предложения.|Предложение категории отправлено.|Не удалось отправить предложение. Попробуйте позже.
id|Usulkan iklan|Usulkan kategori|Usulan kategori untuk iklan baris ON4CRD|Jelaskan kategori yang diinginkan. Klub akan meninjaunya sebelum menambahkannya ke iklan baris.|Usulan kategori baru untuk iklan baris ON4CRD.|Nama kategori|Mis. antena, aksesori, komponen|Nama Anda|E-mail Anda|Detail / alasan|Jelaskan jenis iklan yang terkait atau mengapa kategori ini berguna.|Kirim usulan|Batal|Tutup|Harap lengkapi formulir usulan dengan benar.|Usulan kategori terkirim.|Usulan tidak dapat dikirim. Coba lagi nanti.
ROWS;

$root = __DIR__;
foreach (explode("\n", trim($rows)) as $line) {
    $parts = explode('|', $line);
    $locale = array_shift($parts);
    if (count($parts) !== count($keys)) {
        fwrite(STDERR, sprintf("Invalid field count for %s: %d\n", $locale, count($parts)));
        exit(1);
    }

    $path = $root . '/app/i18n/classifieds/' . $locale . '.php';
    if (!is_file($path)) {
        fwrite(STDERR, "Missing locale file: {$locale}\n");
        exit(1);
    }

    $messages = require $path;
    if (!is_array($messages)) {
        fwrite(STDERR, "Invalid locale file: {$locale}\n");
        exit(1);
    }

    foreach (array_combine($keys, $parts) as $key => $value) {
        $messages[$key] = $value;
    }

    file_put_contents($path, "<?php\nreturn " . var_export($messages, true) . ";\n");
}
