sonar.projectKey=Smartappli_on4crd
sonar.organization=smartappli-github

sonar.exclusions=vendor/**,node_modules/**,assets/vendor/**,playwright-report/**,test-results/**,var/**
sonar.test.inclusions=tests/**
sonar.cpd.exclusions=app/i18n/**,tests/**,assets/sql/**
