const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const { assert } = require('./helpers');

const coveredRoutes = new Set([
  'home',
  'login',
  'register',
  'forgot_password',
  'reset_password',
  'membership',
  'donation',
  'conditions_utilisation',
  'mentions_legales',
  'reglement_interieur',
  'sponsoring',
  'gdpr',
  'search',
  'news',
  'news_view',
  'articles',
  'article',
  'wiki',
  'wiki_view',
  'albums',
  'album',
  'classifieds',
  'chatbot',
  'directory',
  'tools',
  'tools_geocode',
  'committee',
  'press',
  'schools',
  'events',
  'events_feed',
  'event_view',
  'auctions',
  'auction_view',
  'ad_click',
  'relais',
  'code_q',
  'code_cw',
  'bandplan_on3',
  'bandplan_on2',
  'bandplan_harec',
  'newsletter_public',
  'newsletter_unsubscribe',
  'sitemap.xml',
  'robots.txt',
  'llms.txt',
  'ai-index.json',
  'knowledge-graph.jsonld',
  'errors',
  'install.php',
  'logout',
  'toggle_theme',
  'set_language',
  'set_accent',
  'set_theme',
  'idea_submit',
  'footer_contact',
  'dashboard',
  'notifications',
  'save_dashboard',
  'widget_render',
  'dashboard_widget_card',
  'profile',
  'change_password',
  'my_requests',
  'members_library',
  'member_library_preview',
  'member_document_preview',
  'webotheque',
  'presentations',
  'videos',
  'pv',
  'fichiers',
  'telechargements',
  'qsl',
  'qsl_preview',
  'qsl_export',
  'newsletter',
  'settings',
  'classifieds_manage',
  'article_propose',
  'wiki_edit',
  'wiki_propose',
  'auction_bid',
  'ads',
  'admin',
  'admin_permissions',
  'admin_members',
  'admin_newsletters',
  'admin_privacy',
  'admin_modules',
  'admin_articles',
  'admin_committee',
  'admin_wiki',
  'admin_albums',
  'admin_library',
  'admin_webotheque',
  'admin_presentations',
  'admin_videos',
  'admin_pv',
  'admin_fichiers',
  'admin_telechargements',
  'admin_news',
  'admin_press',
  'admin_editorial',
  'admin_translation_reviews',
  'admin_live_feeds',
  'admin_events',
  'admin_events_feed',
  'admin_dinner_reservations',
  'admin_dashboard',
  'admin_auctions',
  'admin_classifieds',
  'admin_ads',
]);

function dispatchedRoutes() {
  const indexPhp = fs.readFileSync(path.join(process.cwd(), 'index.php'), 'utf8');
  const switchRoutes = Array.from(indexPhp.matchAll(/case '([^']+)'\s*:/g), (match) => match[1]);
  const earlyActionRoutes = Array.from(indexPhp.matchAll(/\$route === '([^']+)'/g), (match) => match[1]);

  return Array.from(new Set([...switchRoutes, ...earlyActionRoutes])).sort();
}

test('Selenium couverture: chaque route dispatch exposee par index.php est classee', () => {
  const routes = dispatchedRoutes();
  const missing = routes.filter((route) => !coveredRoutes.has(route));
  assert.deepEqual(missing, [], `Routes non couvertes par la matrice Selenium: ${missing.join(', ')}`);

  const stale = Array.from(coveredRoutes).filter((route) => !routes.includes(route));
  assert.deepEqual(stale, [], `Routes referencees par les tests mais absentes du dispatch: ${stale.join(', ')}`);
});
