<?php
declare(strict_types=1);

return [
'title' => ['fr'=>'Band planning HAREC','en'=>'HAREC band plan','de'=>'HAREC-Bandplan','nl'=>'HAREC-bandplan','es'=>'Plan de banda HAREC','it'=>'Piano di banda HAREC','pt'=>'Plano de banda HAREC','ar'=>'خطة نطاق HAREC','hi'=>'HAREC बैंड प्लान','ja'=>'HAREC バンドプラン','zh'=>'HAREC 频段规划','bn'=>'HAREC ব্যান্ড প্ল্যান','ru'=>'План диапазонов HAREC','id'=>'Rencana band HAREC'],
    'headers' => ['fr'=>['band'=>'Bande','freq'=>'Fréquences (MHz)','modes'=>'Modes','pwr'=>'Puissance max*','notes'=>'Notes'],'en'=>['band'=>'Band','freq'=>'Frequencies (MHz)','modes'=>'Modes','pwr'=>'Max power*','notes'=>'Notes'],'de'=>['band'=>'Band','freq'=>'Frequenzen (MHz)','modes'=>'Betriebsarten','pwr'=>'Max. Leistung*','notes'=>'Hinweise'],'nl'=>['band'=>'Band','freq'=>'Frequenties (MHz)','modes'=>'Modes','pwr'=>'Max vermogen*','notes'=>'Notities'],'es'=>['band'=>'Banda','freq'=>'Frecuencias (MHz)','modes'=>'Modos','pwr'=>'Potencia máx.*','notes'=>'Notas'],'it'=>['band'=>'Banda','freq'=>'Frequenze (MHz)','modes'=>'Modi','pwr'=>'Potenza max*','notes'=>'Note'],'pt'=>['band'=>'Banda','freq'=>'Frequências (MHz)','modes'=>'Modos','pwr'=>'Potência máx.*','notes'=>'Notas'],'ar'=>['band'=>'النطاق','freq'=>'الترددات (MHz)','modes'=>'الأنماط','pwr'=>'القدرة القصوى*','notes'=>'ملاحظات'],'hi'=>['band'=>'बैंड','freq'=>'आवृत्तियाँ (MHz)','modes'=>'मोड','pwr'=>'अधिकतम शक्ति*','notes'=>'टिप्पणियाँ'],'ja'=>['band'=>'バンド','freq'=>'周波数 (MHz)','modes'=>'モード','pwr'=>'最大出力*','notes'=>'備考'],'zh'=>['band'=>'波段','freq'=>'频率 (MHz)','modes'=>'模式','pwr'=>'最大功率*','notes'=>'备注'],'bn'=>['band'=>'ব্যান্ড','freq'=>'ফ্রিকোয়েন্সি (MHz)','modes'=>'মোড','pwr'=>'সর্বোচ্চ শক্তি*','notes'=>'নোট'],'ru'=>['band'=>'Диапазон','freq'=>'Частоты (MHz)','modes'=>'Режимы','pwr'=>'Макс. мощность*','notes'=>'Примечания'],'id'=>['band'=>'Band','freq'=>'Frekuensi (MHz)','modes'=>'Mode','pwr'=>'Daya maks*','notes'=>'Catatan']],
    'rows' => [
['160 m','1.810–2.000','CW/SSB',['fr'=>'Bas de bande majoritairement CW.','en'=>'Lower segment mainly CW.','de'=>'Unteres Segment meist CW.','nl'=>'Onderste segment vooral CW.','es'=>'Segmento inferior mayoritariamente CW.','it'=>'Segmento inferiore principalmente CW.','pt'=>'Segmento inferior maioritariamente CW.','ar'=>'الجزء السفلي من النطاق غالبًا CW.','hi'=>'निचला भाग मुख्यतः CW।','ja'=>'下側セグメントは主にCW。','zh'=>'低端频段主要用于 CW。','bn'=>'নিম্ন অংশ প্রধানত CW।','ru'=>'Нижний сегмент в основном CW.','id'=>'Segmen bawah terutama CW.'],'1500 W PEP'],
['80 m','3.500–3.800','CW/SSB/Data',['fr'=>'NVIS local/régional.','en'=>'Local/regional NVIS.','de'=>'Lokales/regionales NVIS.','nl'=>'Lokaal/regionaal NVIS.','es'=>'NVIS local/regional.','it'=>'NVIS locale/regionale.','pt'=>'NVIS local/regional.','ar'=>'NVIS محلي/إقليمي.','hi'=>'स्थानीय/क्षेत्रीय NVIS।','ja'=>'ローカル/地域 NVIS。','zh'=>'本地/区域 NVIS。','bn'=>'স্থানীয়/আঞ্চলিক NVIS।','ru'=>'Локальный/региональный NVIS.','id'=>'NVIS lokal/regional.'],'1500 W PEP'],
['60 m','5.3515–5.3665','SSB/Data',['fr'=>'Canaux/segments selon publication IBPT.','en'=>'Channels/segments per IBPT publication.','de'=>'Kanäle/Segmente gemäß IBPT-Veröffentlichung.','nl'=>'Kanalen/segmenten volgens IBPT-publicatie.','es'=>'Canales/segmentos según la publicación del IBPT.','it'=>'Canali/segmenti secondo la pubblicazione IBPT.','pt'=>'Canais/segmentos conforme a publicação do IBPT.','ar'=>'قنوات/مقاطع وفق منشور IBPT.','hi'=>'IBPT प्रकाशन के अनुसार चैनल/सेगमेंट।','ja'=>'IBPT 公表に基づくチャネル/セグメント。','zh'=>'信道/分段依据 IBPT 发布。','bn'=>'IBPT প্রকাশনা অনুযায়ী চ্যানেল/সেগমেন্ট।','ru'=>'Каналы/сегменты согласно публикации IBPT.','id'=>'Kanal/segmen sesuai publikasi IBPT.'],'100 W PEP'],
['40 m','7.000–7.200','CW/SSB/Data',['fr'=>'Forte activité internationale.','en'=>'High international activity.','de'=>'Hohe internationale Aktivität.','nl'=>'Hoge internationale activiteit.','es'=>'Alta actividad internacional.','it'=>'Elevata attività internazionale.','pt'=>'Elevada atividade internacional.','ar'=>'نشاط دولي مرتفع.','hi'=>'उच्च अंतरराष्ट्रीय गतिविधि।','ja'=>'国際的な活動が活発。','zh'=>'国际活动频繁。','bn'=>'উচ্চ আন্তর্জাতিক কার্যক্রম।','ru'=>'Высокая международная активность.','id'=>'Aktivitas internasional tinggi.'],'1500 W PEP'],
['30 m','10.100–10.150','CW/Data',['fr'=>'Pas de téléphonie en général.','en'=>'Generally no phone operation.','de'=>'Im Allgemeinen keine Telefonie.','nl'=>'Meestal geen telefonie.','es'=>'Generalmente sin operación de telefonía.','it'=>'Generalmente senza fonia.','pt'=>'Geralmente sem operação de fonia.','ar'=>'عمومًا لا يُسمح بالاتصالات الهاتفية.','hi'=>'आम तौर पर फोन ऑपरेशन नहीं।','ja'=>'通常、電話運用は不可。','zh'=>'通常不允许话音通信。','bn'=>'সাধারণত ফোন অপারেশন নয়।','ru'=>'Обычно без телефонной работы.','id'=>'Umumnya tanpa operasi teleponi.'],'500 W PEP'],
['20 m','14.000–14.350','CW/SSB/Data',['fr'=>'14.074 FT8.','en'=>'14.074 FT8.','de'=>'14,074 FT8.','nl'=>'14.074 FT8.','es'=>'14.074 FT8.','it'=>'14.074 FT8.','pt'=>'14.074 FT8.','ar'=>'14.074 FT8.','hi'=>'14.074 FT8।','ja'=>'14.074 FT8。','zh'=>'14.074 FT8。','bn'=>'14.074 FT8।','ru'=>'14.074 FT8.','id'=>'14.074 FT8.'],'1500 W PEP'],
['17 m','18.068–18.168','CW/SSB/Data',['fr'=>'Bande WARC.','en'=>'WARC band.','de'=>'WARC-Band.','nl'=>'WARC-band.','es'=>'Banda WARC.','it'=>'Banda WARC.','pt'=>'Banda WARC.','ar'=>'نطاق WARC.','hi'=>'WARC बैंड।','ja'=>'WARC バンド。','zh'=>'WARC 波段。','bn'=>'WARC ব্যান্ড।','ru'=>'Диапазон WARC.','id'=>'Band WARC.'],'1500 W PEP'],
['15 m','21.000–21.450','CW/SSB/Data',['fr'=>'Propagation souvent favorable en journée.','en'=>'Propagation often favorable by day.','de'=>'Ausbreitung tagsüber oft günstig.','nl'=>'Propagatie vaak gunstig overdag.','es'=>'Propagación a menudo favorable de día.','it'=>'Propagazione spesso favorevole di giorno.','pt'=>'Propagação frequentemente favorável durante o dia.','ar'=>'الانتشار غالبًا مناسب نهارًا.','hi'=>'दिन में प्रसार अक्सर अनुकूल रहता है।','ja'=>'日中は伝搬条件が良好なことが多い。','zh'=>'白天传播条件通常较好。','bn'=>'দিনে প্রোপাগেশন প্রায়ই অনুকূল থাকে।','ru'=>'Прохождение часто благоприятно днём.','id'=>'Propagasi sering lebih baik pada siang hari.'],'1500 W PEP'],
['12 m','24.890–24.990','CW/SSB/Data',['fr'=>'Bande WARC.','en'=>'WARC band.','de'=>'WARC-Band.','nl'=>'WARC-band.','es'=>'Banda WARC.','it'=>'Banda WARC.','pt'=>'Banda WARC.','ar'=>'نطاق WARC.','hi'=>'WARC बैंड।','ja'=>'WARC バンド。','zh'=>'WARC 波段。','bn'=>'WARC ব্যান্ড।','ru'=>'Диапазон WARC.','id'=>'Band WARC.'],'1500 W PEP'],
['10 m','28.000–29.700','CW/SSB/FM/Data',['fr'=>'Inclut balises et FM locale.','en'=>'Includes beacons and local FM.','de'=>'Enthält Baken und lokalen FM-Betrieb.','nl'=>'Inclusief bakens en lokale FM.','es'=>'Incluye balizas y FM local.','it'=>'Include beacon e FM locale.','pt'=>'Inclui balizas e FM local.','ar'=>'يتضمن المنارات وFM المحلي.','hi'=>'इसमें बीकन और स्थानीय FM शामिल हैं।','ja'=>'ビーコンとローカルFMを含みます。','zh'=>'包含信标和本地 FM。','bn'=>'এতে বিকন এবং স্থানীয় FM অন্তর্ভুক্ত।','ru'=>'Включает маяки и местную FM-связь.','id'=>'Mencakup beacon dan FM lokal.'],'1500 W PEP'],
['6 m','50.000–52.000','CW/SSB/FM/Data',['fr'=>'Ouvertures sporadiques E.','en'=>'Sporadic-E openings.','de'=>'Sporadic-E-Öffnungen.','nl'=>'Sporadic-E-openingen.','es'=>'Aperturas de Esporádica-E.','it'=>'Aperture Sporadico-E.','pt'=>'Aberturas de Esporádica-E.','ar'=>'فتحات E متقطعة.','hi'=>'स्पोराडिक‑E ओपनिंग्स।','ja'=>'スポラディックEのオープン。','zh'=>'散发 E 开通。','bn'=>'স্পোরাডিক‑E ওপেনিং।','ru'=>'Спорадические открытия E.','id'=>'Bukaan Sporadic-E.'],'400 W PEP'],
['2 m','144.000–146.000','FM/SSB/CW',['fr'=>'145.500 appel simplex.','en'=>'145.500 simplex calling.','de'=>'145,500 Simplex-Anruf.','nl'=>'145.500 simplex-oproep.','es'=>'Llamada simplex en 145.500.','it'=>'Chiamata simplex su 145.500.','pt'=>'Chamada simplex em 145.500.','ar'=>'نداء simplex على 145.500.','hi'=>'145.500 पर simplex कॉलिंग।','ja'=>'145.500 はシンプレックス呼出。','zh'=>'145.500 为单工呼叫频率。','bn'=>'145.500 সিমপ্লেক্স কলিং।','ru'=>'145.500 — вызывная simplex-частота.','id'=>'Panggilan simplex di 145.500.'],'120 W PEP'],
['70 cm','430.000–440.000','FM/Relais/Numérique',['fr'=>'Relais analogiques et numériques.','en'=>'Analog and digital repeaters.','de'=>'Analoge und digitale Relais.','nl'=>'Analoge en digitale relais.','es'=>'Repetidores analógicos y digitales.','it'=>'Ripetitori analogici e digitali.','pt'=>'Repetidores analógicos e digitais.','ar'=>'مكررات تناظرية ورقمية.','hi'=>'एनालॉग और डिजिटल रिपीटर।','ja'=>'アナログおよびデジタルのレピータ。','zh'=>'模拟和数字中继。','bn'=>'অ্যানালগ ও ডিজিটাল রিপিটার।','ru'=>'Аналоговые и цифровые ретрансляторы.','id'=>'Repeater analog dan digital.'],'120 W PEP'],
['23 cm','1240–1300','FM/SSB/CW/Data',['fr'=>'Usages partagés selon zones.','en'=>'Shared usage depending on areas.','de'=>'Geteilte Nutzung je nach Region.','nl'=>'Gedeeld gebruik afhankelijk van regio.','es'=>'Uso compartido según las zonas.','it'=>'Uso condiviso secondo le aree.','pt'=>'Uso partilhado consoante as zonas.','ar'=>'استخدامات مشتركة حسب المناطق.','hi'=>'क्षेत्र के अनुसार साझा उपयोग।','ja'=>'地域により共用用途。','zh'=>'按地区共享使用。','bn'=>'এলাকা ভেদে যৌথ ব্যবহার।','ru'=>'Совместное использование в зависимости от региона.','id'=>'Penggunaan bersama tergantung wilayah.'],'120 W PEP'],
]
];
