<?php
declare(strict_types=1);

return [
    'locators' => [
        ['id' => 'tool-grid', 'title_key' => 'grid_title'],
        ['id' => 'tool-distance', 'title_key' => 'distance'],
    ],
    'conversion' => [
        ['id' => 'tool-freq-wave', 'title_pattern' => 'conv_dot', 'left_key' => 'conv', 'right_key' => 'freq_wave'],
        ['id' => 'tool-power', 'title_pattern' => 'conv_dot', 'left_key' => 'conv', 'right_key' => 'power'],
        ['id' => 'tool-filter', 'title_key' => 'filter_calc'],
        ['id' => 'tool-balun', 'title_key' => 'balun_calc'],
        ['id' => 'tool-swr', 'title_key' => 'swr_calc'],
        ['id' => 'tool-fspl', 'title_key' => 'fspl_calc'],
        ['id' => 'tool-runtime', 'title_key' => 'runtime_calc'],
        ['id' => 'tool-coax', 'title_key' => 'coax_calc'],
        ['id' => 'tool-bandwidth', 'title_key' => 'bandwidth_calc'],
        ['id' => 'tool-duty', 'title_key' => 'duty_cycle_calc'],
        ['id' => 'tool-divider', 'title_key' => 'divider_calc'],
        ['id' => 'tool-resistor-combo', 'title_key' => 'resistor_combo_calc'],
        ['id' => 'tool-mismatch', 'title_key' => 'mismatch_loss_calc'],
        ['id' => 'tool-xl', 'title_key' => 'xl_calc'],
        ['id' => 'tool-xc', 'title_key' => 'xc_calc'],
        ['id' => 'tool-vpp-vrms', 'title_key' => 'vpp_vrms_calc'],
        ['id' => 'tool-vrms-vpp', 'title_key' => 'vrms_vpp_calc'],
        ['id' => 'tool-vpk-vrms', 'title_key' => 'vpk_vrms_calc'],
        ['id' => 'tool-kw-w', 'title_key' => 'kw_w_calc'],
        ['id' => 'tool-w-kw', 'title_key' => 'w_kw_calc'],
        ['id' => 'tool-hz-khz', 'title_key' => 'hz_khz_calc'],
        ['id' => 'tool-khz-mhz', 'title_key' => 'khz_mhz_calc'],
        ['id' => 'tool-mhz-ghz', 'title_key' => 'mhz_ghz_calc'],
        ['id' => 'tool-in-mm', 'title_key' => 'in_mm_calc'],
        ['id' => 'tool-ft-m', 'title_key' => 'ft_m_calc'],
        ['id' => 'tool-c-f', 'title_key' => 'c_f_calc'],
        ['id' => 'tool-f-c', 'title_key' => 'f_c_calc'],
        ['id' => 'tool-pa-db', 'title_key' => 'pa_db_calc'],
        ['id' => 'tool-db-pa', 'title_key' => 'db_pa_calc'],
        ['id' => 'tool-j-wh', 'title_key' => 'j_wh_calc'],
        ['id' => 'tool-wh-j', 'title_key' => 'wh_j_calc'],
        ['id' => 'tool-ms-s', 'title_key' => 'ms_s_calc'],
        ['id' => 'tool-s-ms', 'title_key' => 's_ms_calc'],
        ['id' => 'tool-rpm-rps', 'title_key' => 'rpm_rps_calc'],
        ['id' => 'tool-rps-rpm', 'title_key' => 'rps_rpm_calc'],
        ['id' => 'tool-sunit-dbuv', 'title_key' => 'sunit_dbuv_calc'],
        ['id' => 'tool-dbuv-sunit', 'title_key' => 'dbuv_sunit_calc'],
    ],
    'antenna' => [
        ['id' => 'tool-quarter-wave', 'title_key' => 'quarter_wave_calc'],
        ['id' => 'tool-erp', 'title_key' => 'erp_calc'],
        ['id' => 'tool-dipole', 'title_key' => 'dipole_calc'],
    ],
    'power' => [
        ['id' => 'tool-solar', 'title_key' => 'solar_calc'],
        ['id' => 'tool-battery-current', 'title_key' => 'battery_current_calc'],
    ],
    'advanced_propagation' => [
        ['id' => 'tool-muf', 'title_key' => 'muftool_calc'],
        ['id' => 'tool-skip', 'title_key' => 'skip_calc'],
    ],
    'rf_measures' => [
        ['id' => 'tool-eirp', 'title_key' => 'eirp_calc'],
    ],
    'radio_math' => [
        ['id' => 'tool-db-sum', 'title_key' => 'db_sum_calc'],
        ['id' => 'tool-dbuv', 'title_key' => 'dbuv_calc'],
        ['id' => 'tool-gain-conv', 'title_key' => 'gain_conv_calc'],
        ['id' => 'tool-dbw', 'title' => 'dBm ↔ dBW'],
        ['id' => 'tool-ohm-law', 'title_key' => 'ohm_law_calc'],
        ['id' => 'tool-link-budget', 'title_key' => 'link_budget_calc'],
    ],
];
