<?php
declare(strict_types=1);

/**
 * @return array<int, array{
 *   route:string,
 *   title:array<string,string>,
 *   desc:array<string,string>,
 *   module?:string,
 *   permission?:string,
 *   audience?:array<string,string>,
 *   icon?:array<string,string>|string
 * }>
 */
function admin_module_cards_catalog(): array
{
    $catalog = [
        ['route' => 'admin_modules', 'title' => ['fr' => 'Modules', 'en' => 'Modules', 'de' => 'Module', 'nl' => 'Modules', 'es' => 'Módulos', 'it' => 'Moduli', 'pt' => 'Módulos', 'ar' => 'الوحدات', 'bn' => 'মডিউল', 'hi' => 'मॉड्यूल', 'id' => 'Modul', 'ja' => 'モジュール', 'ru' => 'Модули', 'zh' => '模块'], 'desc' => ['fr' => 'Activation, désactivation et pilotage global des modules.', 'en' => 'Enable, disable and globally manage modules.', 'de' => 'Module aktivieren, deaktivieren und zentral steuern.', 'nl' => 'Modules activeren, deactiveren en centraal beheren.', 'es' => 'Activar, desactivar y gestionar globalmente los módulos.', 'it' => 'Attiva, disattiva e gestisci globalmente i moduli.', 'pt' => 'Ative, desative e gerencie globalmente os módulos.', 'ar' => 'تفعيل وتعطيل وإدارة الوحدات بشكل عام.', 'bn' => 'মডিউল সক্রিয়, নিষ্ক্রিয় ও কেন্দ্রীয়ভাবে পরিচালনা করুন।', 'hi' => 'मॉड्यूल सक्षम/अक्षम करें और वैश्विक रूप से प्रबंधित करें।', 'id' => 'Aktifkan, nonaktifkan, dan kelola modul secara global.', 'ja' => 'モジュールの有効化・無効化と全体管理。', 'ru' => 'Включение, отключение и общее управление модулями.', 'zh' => '启用、禁用并统一管理模块。'], 'permission' => 'modules.manage'],
        ['route' => 'admin_members', 'title' => ['fr' => 'Gestion des membres', 'en' => 'Member management', 'de' => 'Mitgliederverwaltung', 'nl' => 'Ledenbeheer', 'es' => 'Gestión de socios', 'it' => 'Gestione membri', 'pt' => 'Gestão de membros', 'ar' => 'إدارة الأعضاء', 'bn' => 'সদস্য ব্যবস্থাপনা', 'hi' => 'सदस्य प्रबंधन', 'id' => 'Manajemen anggota', 'ja' => 'メンバー管理', 'ru' => 'Управление участниками', 'zh' => '成员管理'], 'desc' => ['fr' => 'Profils membres, statut actif et comité.', 'en' => 'Member profiles, active status and committee.', 'de' => 'Mitgliederprofile, Aktivstatus und Komitee.', 'nl' => 'Ledenprofielen, actieve status en comité.', 'es' => 'Perfiles de socios, estado activo y comité.', 'it' => 'Profili membri, stato attivo e comitato.', 'pt' => 'Perfis de membros, estado ativo e comité.', 'ar' => 'ملفات الأعضاء والحالة النشطة واللجنة.', 'bn' => 'সদস্য প্রোফাইল, সক্রিয় অবস্থা ও কমিটি।', 'hi' => 'सदस्य प्रोफ़ाइल, सक्रिय स्थिति और समिति।', 'id' => 'Profil anggota, status aktif, dan komite.', 'ja' => 'メンバープロファイル、アクティブ状態、委員会。', 'ru' => 'Профили участников, активный статус и комитет.', 'zh' => '成员档案、活跃状态和委员会。']],
        ['route' => 'admin_permissions', 'title' => ['fr' => 'Rôles & permissions', 'en' => 'Roles & permissions', 'de' => 'Rollen & Berechtigungen', 'nl' => 'Rollen & rechten', 'es' => 'Roles y permisos', 'it' => 'Ruoli e permessi', 'pt' => 'Funções e permissões', 'ar' => 'الأدوار والصلاحيات', 'bn' => 'ভূমিকা ও অনুমতি', 'hi' => 'भूमिकाएँ और अनुमतियाँ', 'id' => 'Peran & izin', 'ja' => 'ロールと権限', 'ru' => 'Роли и разрешения', 'zh' => '角色与权限'], 'desc' => ['fr' => 'Attribution des rôles et matrice des permissions.', 'en' => 'Role assignment and permissions matrix.', 'de' => 'Rollenzuweisung und Berechtigungsmatrix.', 'nl' => 'Roltoewijzing en rechtenmatrix.', 'es' => 'Asignación de roles y matriz de permisos.', 'it' => 'Assegnazione dei ruoli e matrice dei permessi.', 'pt' => 'Atribuição de funções e matriz de permissões.', 'ar' => 'تعيين الأدوار ومصفوفة الصلاحيات.', 'bn' => 'ভূমিকা নির্ধারণ ও অনুমতি ম্যাট্রিক্স।', 'hi' => 'भूमिका असाइनमेंट और अनुमति मैट्रिक्स।', 'id' => 'Penetapan peran dan matriks izin.', 'ja' => 'ロール割り当てと権限マトリクス。', 'ru' => 'Назначение ролей и матрица разрешений.', 'zh' => '角色分配与权限矩阵。']],
        ['route' => 'admin_news', 'title' => ['fr' => 'Actualités', 'en' => 'News', 'de' => 'Neuigkeiten', 'nl' => 'Nieuws', 'es' => 'Noticias', 'it' => 'Notizie', 'pt' => 'Notícias', 'ar' => 'الأخبار', 'bn' => 'সংবাদ', 'hi' => 'समाचार', 'id' => 'Berita', 'ja' => 'ニュース', 'ru' => 'Новости', 'zh' => '新闻'], 'desc' => ['fr' => 'Sections, rédaction et modération.', 'en' => 'Sections, writing and moderation.', 'de' => 'Bereiche, Redaktion und Moderation.', 'nl' => 'Secties, redactie en moderatie.', 'es' => 'Secciones, redacción y moderación.', 'it' => 'Sezioni, redazione e moderazione.', 'pt' => 'Secções, redação e moderação.', 'ar' => 'الأقسام والتحرير والإشراف.', 'bn' => 'সেকশন, লেখা ও মডারেশন।', 'hi' => 'सेक्शन, लेखन और मॉडरेशन।', 'id' => 'Bagian, penulisan, dan moderasi.', 'ja' => 'セクション、執筆、モデレーション。', 'ru' => 'Разделы, редактура и модерация.', 'zh' => '栏目、撰写与审核。'], 'module' => 'news'],
        ['route' => 'admin_articles', 'title' => ['fr' => 'Articles', 'en' => 'Articles', 'de' => 'Artikel', 'nl' => 'Artikels', 'es' => 'Artículos', 'it' => 'Articoli', 'pt' => 'Artigos', 'ar' => 'المقالات', 'bn' => 'প্রবন্ধ', 'hi' => 'लेख', 'id' => 'Artikel', 'ja' => '記事', 'ru' => 'Статьи', 'zh' => '文章'], 'desc' => ['fr' => 'Articles techniques publics.', 'en' => 'Public technical articles.', 'de' => 'Öffentliche technische Artikel.', 'nl' => 'Publieke technische artikels.', 'es' => 'Artículos técnicos públicos.', 'it' => 'Articoli tecnici pubblici.', 'pt' => 'Artigos técnicos públicos.', 'ar' => 'مقالات تقنية عامة.', 'bn' => 'সর্বসাধারণের জন্য প্রযুক্তিগত প্রবন্ধ।', 'hi' => 'सार्वजनिक तकनीकी लेख।', 'id' => 'Artikel teknis publik.', 'ja' => '公開技術記事。', 'ru' => 'Публичные технические статьи.', 'zh' => '公开技术文章。'], 'module' => 'articles'],
        ['route' => 'admin_committee', 'title' => ['fr' => 'Comité', 'en' => 'Committee', 'de' => 'Komitee', 'nl' => 'Comité', 'es' => 'Comité', 'it' => 'Comitato', 'pt' => 'Comité', 'ar' => 'اللجنة', 'bn' => 'কমিটি', 'hi' => 'समिति', 'id' => 'Komite', 'ja' => '委員会', 'ru' => 'Комитет', 'zh' => '委员会'], 'desc' => ['fr' => 'Membres du comité, rôle, ordre et biographie.', 'en' => 'Committee members, role, order and biography.', 'de' => 'Komiteemitglieder, Rolle, Reihenfolge und Biografie.', 'nl' => 'Comitéleden, rol, volgorde en biografie.', 'es' => 'Miembros del comité, rol, orden y biografía.', 'it' => 'Membri del comitato, ruolo, ordine e biografia.', 'pt' => 'Membros do comité, função, ordem e biografia.', 'ar' => 'أعضاء اللجنة والأدوار والترتيب والسيرة.', 'bn' => 'কমিটির সদস্য, ভূমিকা, ক্রম ও জীবনী।', 'hi' => 'समिति सदस्य, भूमिका, क्रम और जीवनी।', 'id' => 'Anggota komite, peran, urutan, dan biografi.', 'ja' => '委員会メンバー、役割、順序、経歴。', 'ru' => 'Члены комитета, роль, порядок и биография.', 'zh' => '委员会成员、角色、顺序和简介。'], 'module' => 'committee'],
        ['route' => 'admin_press', 'title' => ['fr' => 'Presse', 'en' => 'Press', 'de' => 'Presse', 'nl' => 'Pers', 'es' => 'Prensa', 'it' => 'Stampa', 'pt' => 'Imprensa', 'ar' => 'الصحافة', 'bn' => 'প্রেস', 'hi' => 'प्रेस', 'id' => 'Pers', 'ja' => 'プレス', 'ru' => 'Пресса', 'zh' => '媒体'], 'desc' => ['fr' => 'Contacts presse, communiqués datés et documents téléchargeables.', 'en' => 'Press contacts, dated releases and downloadable documents.', 'de' => 'Pressekontakte, datierte Mitteilungen und Downloads.', 'nl' => 'Perscontacten, gedateerde berichten en downloads.', 'es' => 'Contactos de prensa, comunicados fechados y documentos descargables.', 'it' => 'Contatti stampa, comunicati datati e documenti scaricabili.', 'pt' => 'Contactos de imprensa, comunicados datados e documentos descarregáveis.', 'ar' => 'جهات اتصال الصحافة وبيانات مؤرخة ووثائق قابلة للتنزيل.', 'bn' => 'প্রেস যোগাযোগ, তারিখযুক্ত বিজ্ঞপ্তি ও ডাউনলোডযোগ্য নথি।', 'hi' => 'प्रेस संपर्क, दिनांकित विज्ञप्तियाँ और डाउनलोड करने योग्य दस्तावेज़।', 'id' => 'Kontak pers, rilis bertanggal, dan dokumen yang dapat diunduh.', 'ja' => '報道連絡先、日付付きリリース、ダウンロード可能な資料。', 'ru' => 'Контакты для прессы, датированные релизы и загружаемые документы.', 'zh' => '媒体联系人、带日期的公告和可下载文档。'], 'module' => 'press'],
        ['route' => 'admin_events', 'title' => ['fr' => 'Agenda', 'en' => 'Agenda', 'de' => 'Agenda', 'nl' => 'Agenda', 'es' => 'Agenda', 'it' => 'Agenda', 'pt' => 'Agenda', 'ar' => 'الجدول', 'bn' => 'সূচি', 'hi' => 'कार्यसूची', 'id' => 'Kalender kegiatan', 'ja' => '予定', 'ru' => 'Повестка', 'zh' => '日程'], 'desc' => ['fr' => 'Événements du club et contests locaux affichés dans les widgets live.', 'en' => 'Club events and local contests shown in live widgets.', 'de' => 'Clubveranstaltungen und lokale Contests in Live-Widgets.', 'nl' => 'Clubevenementen en lokale contests in live widgets.', 'es' => 'Eventos del club y concursos locales mostrados en widgets en vivo.', 'it' => 'Eventi del club e contest locali mostrati nei widget live.', 'pt' => 'Eventos do clube e concursos locais exibidos em widgets ao vivo.', 'ar' => 'فعاليات النادي والمسابقات المحلية المعروضة في الأدوات الحية.', 'bn' => 'লাইভ উইজেটে প্রদর্শিত ক্লাব ইভেন্ট ও স্থানীয় কনটেস্ট।', 'hi' => 'लाइव विजेट्स में दिखाए जाने वाले क्लब इवेंट और स्थानीय प्रतियोगिताएँ।', 'id' => 'Acara klub dan kontes lokal yang ditampilkan di widget langsung.', 'ja' => 'ライブウィジェットに表示されるクラブイベントと地域コンテスト。', 'ru' => 'События клуба и местные контесты в live-виджетах.', 'zh' => '在实时小组件中显示的俱乐部活动和本地竞赛。'], 'module' => 'events'],
        ['route' => 'admin_dinner_reservations', 'title' => ['fr' => 'Dîner annuel', 'en' => 'Annual dinner', 'de' => 'Jahresessen', 'nl' => 'Jaarlijks diner', 'es' => 'Cena anual', 'it' => 'Cena annuale', 'pt' => 'Jantar anual', 'ar' => 'العشاء السنوي', 'bn' => 'বার্ষিক ডিনার', 'hi' => 'वार्षिक रात्रिभोज', 'id' => 'Makan malam tahunan', 'ja' => '年次ディナー', 'ru' => 'Ежегодный ужин', 'zh' => '年度晚宴'], 'desc' => ['fr' => 'Réservations, lignes repas/dessert, quantités et total automatique.', 'en' => 'Reservations, meal/dessert lines, quantities and auto total.', 'de' => 'Reservierungen, Menüzeilen, Mengen und automatische Summe.', 'nl' => 'Reservaties, maaltijdregels, aantallen en automatisch totaal.', 'es' => 'Reservas, líneas de comida/postre, cantidades y total automático.', 'it' => 'Prenotazioni, voci pasto/dessert, quantità e totale automatico.', 'pt' => 'Reservas, linhas de refeição/sobremesa, quantidades e total automático.', 'ar' => 'الحجوزات وبنود الوجبات/الحلوى والكميات والإجمالي التلقائي.', 'bn' => 'রিজার্ভেশন, খাবার/ডেজার্ট লাইন, পরিমাণ ও স্বয়ংক্রিয় মোট।', 'hi' => 'आरक्षण, भोजन/डेज़र्ट पंक्तियाँ, मात्राएँ और स्वचालित कुल।', 'id' => 'Reservasi, baris menu/hidangan penutup, jumlah, dan total otomatis.', 'ja' => '予約、食事/デザート項目、数量、自動合計。', 'ru' => 'Бронирования, позиции меню/десерта, количества и автосумма.', 'zh' => '预订、餐食/甜点条目、数量和自动总计。'], 'module' => 'events', 'permission' => 'events.manage'],
        ['route' => 'admin_auctions', 'title' => ['fr' => 'Enchères', 'en' => 'Auctions', 'de' => 'Auktionen', 'nl' => 'Veilingen', 'es' => 'Subastas', 'it' => 'Aste', 'pt' => 'Leilões', 'ar' => 'المزادات', 'bn' => 'নিলাম', 'hi' => 'नीलामी', 'id' => 'Lelang', 'ja' => 'オークション', 'ru' => 'Аукционы', 'zh' => '拍卖'], 'desc' => ['fr' => 'Lots, planification, offres et clôture.', 'en' => 'Lots, scheduling, bids and closing.', 'de' => 'Lose, Planung, Gebote und Abschluss.', 'nl' => 'Kavels, planning, biedingen en afsluiting.', 'es' => 'Lotes, planificación, pujas y cierre.', 'it' => 'Lotti, pianificazione, offerte e chiusura.', 'pt' => 'Lotes, planeamento, licitações e fecho.', 'ar' => 'الدفعات والجدولة والعروض والإغلاق.', 'bn' => 'লট, পরিকল্পনা, বিড ও সমাপ্তি।', 'hi' => 'लॉट, शेड्यूलिंग, बोलियाँ और समापन।', 'id' => 'Lot, penjadwalan, penawaran, dan penutupan.', 'ja' => 'ロット、スケジュール、入札、終了。', 'ru' => 'Лоты, планирование, ставки и закрытие.', 'zh' => '拍品、排期、出价与结束。'], 'module' => 'auctions', 'permission' => 'auctions.manage'],
        ['route' => 'admin_editorial', 'title' => ['fr' => 'Éditorial multilingue', 'en' => 'Multilingual editorial', 'de' => 'Mehrsprachige Redaktion', 'nl' => 'Meertalige redactie', 'es' => 'Editorial multilingüe', 'it' => 'Editoriale multilingue', 'pt' => 'Editorial multilíngue', 'ar' => 'تحرير متعدد اللغات', 'bn' => 'বহুভাষিক সম্পাদকীয়', 'hi' => 'बहुभाषी संपादकीय', 'id' => 'Editorial multibahasa', 'ja' => '多言語エディトリアル', 'ru' => 'Многоязычная редакция', 'zh' => '多语言编辑'], 'desc' => ['fr' => 'Français source, traduction auto EN/DE/NL et relecture manuelle.', 'en' => 'French source, EN/DE/NL auto translation and manual review.', 'de' => 'Französische Quelle, automatische Übersetzung und Review.', 'nl' => 'Franse bron, automatische vertaling en manuele review.', 'es' => 'Fuente en francés, traducción automática EN/DE/NL y revisión manual.', 'it' => 'Fonte francese, traduzione automatica EN/DE/NL e revisione manuale.', 'pt' => 'Fonte em francês, tradução automática EN/DE/NL e revisão manual.', 'ar' => 'مصدر بالفرنسية مع ترجمة آلية EN/DE/NL ومراجعة يدوية.', 'bn' => 'ফরাসি সোর্স, EN/DE/NL স্বয়ংক্রিয় অনুবাদ ও ম্যানুয়াল রিভিউ।', 'hi' => 'फ़्रेंच स्रोत, EN/DE/NL ऑटो अनुवाद और मैनुअल समीक्षा।', 'id' => 'Sumber bahasa Prancis, terjemahan otomatis EN/DE/NL, dan tinjauan manual.', 'ja' => 'フランス語原文、EN/DE/NL自動翻訳、手動レビュー。', 'ru' => 'Французский источник, авто-перевод EN/DE/NL и ручная проверка.', 'zh' => '法语源文，EN/DE/NL 自动翻译与人工校对。']],
        ['route' => 'admin_translation_reviews', 'title' => ['fr' => 'Relecture linguistique', 'en' => 'Translation reviews', 'de' => 'Sprachliche Prüfung', 'nl' => 'Taalreview', 'es' => 'Revisión de traducciones', 'it' => 'Revisione traduzioni', 'pt' => 'Revisão de traduções', 'ar' => 'مراجعة الترجمات', 'bn' => 'অনুবাদ পর্যালোচনা', 'hi' => 'अनुवाद समीक्षा', 'id' => 'Tinjauan terjemahan', 'ja' => '翻訳レビュー', 'ru' => 'Проверка переводов', 'zh' => '翻译审校'], 'desc' => ['fr' => 'Workflow de validation des traductions des actualités et articles.', 'en' => 'Validation workflow for news/article translations.', 'de' => 'Freigabe-Workflow für News-/Artikelübersetzungen.', 'nl' => 'Validatieworkflow voor vertalingen van nieuws/artikels.', 'es' => 'Flujo de validación para traducciones de noticias y artículos.', 'it' => 'Flusso di validazione per traduzioni di notizie e articoli.', 'pt' => 'Fluxo de validação para traduções de notícias e artigos.', 'ar' => 'سير عمل اعتماد ترجمات الأخبار والمقالات.', 'bn' => 'সংবাদ/প্রবন্ধ অনুবাদের যাচাইকরণ ওয়ার্কফ্লো।', 'hi' => 'समाचार/लेख अनुवाद के लिए सत्यापन कार्यप्रवाह।', 'id' => 'Alur validasi untuk terjemahan berita/artikel.', 'ja' => 'ニュース/記事翻訳の承認ワークフロー。', 'ru' => 'Процесс валидации переводов новостей и статей.', 'zh' => '新闻/文章翻译的校验工作流。']],
        ['route' => 'admin_dashboard', 'title' => ['fr' => 'Widgets dashboard', 'en' => 'Dashboard widgets', 'de' => 'Dashboard-Widgets', 'nl' => 'Dashboard-widgets', 'es' => 'Widgets del panel', 'it' => 'Widget dashboard', 'pt' => 'Widgets do painel', 'ar' => 'عناصر لوحة التحكم', 'bn' => 'ড্যাশবোর্ড উইজেট', 'hi' => 'डैशबोर्ड विजेट्स', 'id' => 'Widget dasbor', 'ja' => 'ダッシュボードウィジェット', 'ru' => 'Виджеты панели', 'zh' => '仪表板小组件'], 'desc' => ['fr' => 'Activation des widgets disponibles pour les membres.', 'en' => 'Enable widgets available to members.', 'de' => 'Aktivierung verfügbarer Widgets für Mitglieder.', 'nl' => 'Activeer widgets beschikbaar voor leden.', 'es' => 'Activar widgets disponibles para socios.', 'it' => 'Attiva i widget disponibili per i membri.', 'pt' => 'Ativar widgets disponíveis para membros.', 'ar' => 'تفعيل الأدوات المتاحة للأعضاء.', 'bn' => 'সদস্যদের জন্য উপলভ্য উইজেট সক্রিয় করুন।', 'hi' => 'सदस्यों के लिए उपलब्ध विजेट सक्रिय करें।', 'id' => 'Aktifkan widget yang tersedia untuk anggota.', 'ja' => 'メンバー向けウィジェットを有効化。', 'ru' => 'Включение доступных участникам виджетов.', 'zh' => '启用会员可用的小组件。'], 'module' => 'dashboard', 'permission' => 'admin.access'],
        ['route' => 'admin_live_feeds', 'title' => ['fr' => 'Flux live', 'en' => 'Live feeds', 'de' => 'Live-Feeds', 'nl' => 'Live feeds', 'es' => 'Feeds en vivo', 'it' => 'Feed live', 'pt' => 'Feeds ao vivo', 'ar' => 'التدفقات المباشرة', 'bn' => 'লাইভ ফিড', 'hi' => 'लाइव फ़ीड', 'id' => 'Feed langsung', 'ja' => 'ライブフィード', 'ru' => 'Живые ленты', 'zh' => '实时流'], 'desc' => ['fr' => 'Pilotage fin des flux radioamateur, TTL, URLs et activation.', 'en' => 'Fine control of radio feeds, TTL, URLs and activation.', 'de' => 'Feinsteuerung von Funk-Feeds, TTL, URLs und Aktivierung.', 'nl' => 'Fijn beheer van radiofeeds, TTL, URL’s en activatie.', 'es' => 'Control preciso de feeds de radio, TTL, URLs y activación.', 'it' => 'Controllo avanzato dei feed radio, TTL, URL e attivazione.', 'pt' => 'Controlo avançado de feeds de rádio, TTL, URLs e ativação.', 'ar' => 'تحكم دقيق في تدفقات الراديو وTTL وعناوين URL والتفعيل.', 'bn' => 'রেডিও ফিড, TTL, URL ও সক্রিয়করণের সূক্ষ্ম নিয়ন্ত্রণ।', 'hi' => 'रेडियो फ़ीड, TTL, URL और सक्रियण का सूक्ष्म नियंत्रण।', 'id' => 'Kontrol rinci feed radio, TTL, URL, dan aktivasi.', 'ja' => '無線フィード、TTL、URL、有効化の詳細管理。', 'ru' => 'Тонкая настройка радио-лент, TTL, URL и активации.', 'zh' => '精细控制无线电流、TTL、URL 与启用。']],
        ['route' => 'admin_newsletters', 'title' => ['fr' => 'Newsletter', 'en' => 'Newsletter', 'de' => 'Newsletter', 'nl' => 'Nieuwsbrief', 'es' => 'Boletín', 'it' => 'Newsletter', 'pt' => 'Newsletter', 'ar' => 'النشرة البريدية', 'bn' => 'নিউজলেটার', 'hi' => 'न्यूज़लेटर', 'id' => 'Buletin', 'ja' => 'ニュースレター', 'ru' => 'Рассылка', 'zh' => '通讯'], 'desc' => ['fr' => 'Abonnés, import CSV et campagnes email.', 'en' => 'Subscribers, CSV import and email campaigns.', 'de' => 'Abonnenten, CSV-Import und E-Mail-Kampagnen.', 'nl' => 'Abonnees, CSV-import en e-mailcampagnes.', 'es' => 'Suscriptores, importación CSV y campañas de correo.', 'it' => 'Iscritti, import CSV e campagne email.', 'pt' => 'Subscritores, importação CSV e campanhas de email.', 'ar' => 'المشتركون واستيراد CSV وحملات البريد الإلكتروني.', 'bn' => 'সাবস্ক্রাইবার, CSV ইমপোর্ট ও ইমেইল ক্যাম্পেইন।', 'hi' => 'सदस्य, CSV आयात और ईमेल अभियान।', 'id' => 'Pelanggan, impor CSV, dan kampanye email.', 'ja' => '購読者、CSVインポート、メール配信キャンペーン。', 'ru' => 'Подписчики, импорт CSV и email-кампании.', 'zh' => '订阅者、CSV 导入和邮件活动。']],
        ['route' => 'admin_wiki', 'title' => ['fr' => 'Wiki', 'en' => 'Wiki', 'de' => 'Wiki', 'nl' => 'Wiki', 'es' => 'Wiki', 'it' => 'Wiki', 'pt' => 'Wiki', 'ar' => 'الويكي', 'bn' => 'উইকি', 'hi' => 'विकी', 'id' => 'Wiki kolaboratif', 'ja' => '共同Wiki', 'ru' => 'Вики', 'zh' => '维基'], 'desc' => ['fr' => 'Pages collaboratives et révisions.', 'en' => 'Collaborative pages and revisions.', 'de' => 'Kollaborative Seiten und Revisionen.', 'nl' => 'Samenwerkingspagina’s en revisies.', 'es' => 'Páginas colaborativas y revisiones.', 'it' => 'Pagine collaborative e revisioni.', 'pt' => 'Páginas colaborativas e revisões.', 'ar' => 'صفحات تعاونية ومراجعات.', 'bn' => 'সহযোগী পৃষ্ঠা ও রিভিশন।', 'hi' => 'सहयोगी पृष्ठ और संशोधन।', 'id' => 'Halaman kolaboratif dan revisi.', 'ja' => '共同編集ページと改訂履歴。', 'ru' => 'Совместные страницы и ревизии.', 'zh' => '协作页面与修订。'], 'module' => 'wiki'],
        ['route' => 'admin_albums', 'title' => ['fr' => 'Albums', 'en' => 'Albums', 'de' => 'Alben', 'nl' => 'Albums', 'es' => 'Álbumes', 'it' => 'Album', 'pt' => 'Álbuns', 'ar' => 'الألبومات', 'bn' => 'অ্যালবাম', 'hi' => 'एल्बम', 'id' => 'Album', 'ja' => 'アルバム', 'ru' => 'Альбомы', 'zh' => '相册'], 'desc' => ['fr' => 'Galerie publique et synchro sociale.', 'en' => 'Public gallery and social sync.', 'de' => 'Öffentliche Galerie und Social-Sync.', 'nl' => 'Publieke galerij en sociale sync.', 'es' => 'Galería pública y sincronización social.', 'it' => 'Galleria pubblica e sincronizzazione social.', 'pt' => 'Galeria pública e sincronização social.', 'ar' => 'معرض عام ومزامنة اجتماعية.', 'bn' => 'পাবলিক গ্যালারি ও সোশ্যাল সিঙ্ক।', 'hi' => 'सार्वजनिक गैलरी और सोशल सिंक।', 'id' => 'Galeri publik dan sinkronisasi sosial.', 'ja' => '公開ギャラリーとソーシャル同期。', 'ru' => 'Публичная галерея и социальная синхронизация.', 'zh' => '公开图库与社交同步。'], 'module' => 'albums'],
        ['route' => 'admin_library', 'title' => ['fr' => 'Bibliothèque', 'en' => 'Library', 'de' => 'Bibliothek', 'nl' => 'Bibliotheek', 'es' => 'Biblioteca', 'it' => 'Biblioteca', 'pt' => 'Biblioteca', 'ar' => 'المكتبة', 'bn' => 'লাইব্রেরি', 'hi' => 'पुस्तकालय', 'id' => 'Perpustakaan', 'ja' => 'ライブラリ', 'ru' => 'Библиотека', 'zh' => '资料库'], 'desc' => ['fr' => 'Gestion des documents PDF de la bibliothèque membres.', 'en' => 'Manage PDF documents from the members library.', 'de' => 'Verwaltung der PDF-Dokumente der Mitgliederbibliothek.', 'nl' => 'Beheer van PDF-documenten uit de ledenbibliotheek.', 'es' => 'Gestión de documentos PDF de la biblioteca de socios.', 'it' => 'Gestione dei documenti PDF della biblioteca membri.', 'pt' => 'Gestão de documentos PDF da biblioteca de membros.', 'ar' => 'إدارة مستندات PDF لمكتبة الأعضاء.', 'bn' => 'সদস্য লাইব্রেরির PDF নথি ব্যবস্থাপনা।', 'hi' => 'सदस्य पुस्तकालय के PDF दस्तावेज़ प्रबंधन।', 'id' => 'Kelola dokumen PDF dari perpustakaan anggota.', 'ja' => '会員ライブラリのPDF文書を管理。', 'ru' => 'Управление PDF-документами библиотеки участников.', 'zh' => '管理会员资料库中的 PDF 文档。'], 'permission' => 'admin.access'],
        ['route' => 'admin_ads', 'title' => ['fr' => 'Publicités', 'en' => 'Ads', 'de' => 'Werbung', 'nl' => 'Advertenties', 'es' => 'Publicidad', 'it' => 'Pubblicità', 'pt' => 'Publicidade', 'ar' => 'الإعلانات', 'bn' => 'বিজ্ঞাপন', 'hi' => 'विज्ञापन', 'id' => 'Iklan', 'ja' => '広告', 'ru' => 'Реклама', 'zh' => '广告'], 'desc' => ['fr' => 'Régie publicitaire, placements et statistiques.', 'en' => 'Ad inventory, placements and statistics.', 'de' => 'Werbeverwaltung, Platzierungen und Statistiken.', 'nl' => 'Advertentiebeheer, plaatsingen en statistieken.', 'es' => 'Inventario publicitario, ubicaciones y estadísticas.', 'it' => 'Inventario pubblicitario, posizionamenti e statistiche.', 'pt' => 'Inventário publicitário, posicionamentos e estatísticas.', 'ar' => 'إدارة المخزون الإعلاني والمواضع والإحصاءات.', 'bn' => 'বিজ্ঞাপন ইনভেন্টরি, প্লেসমেন্ট ও পরিসংখ্যান।', 'hi' => 'विज्ञापन इन्वेंटरी, प्लेसमेंट और आँकड़े।', 'id' => 'Inventaris iklan, penempatan, dan statistik.', 'ja' => '広告在庫、配置、統計。', 'ru' => 'Рекламный инвентарь, размещения и статистика.', 'zh' => '广告库存、投放位与统计。'], 'module' => 'advertising'],
        ['route' => 'admin_privacy', 'title' => ['fr' => 'RGPD', 'en' => 'GDPR'], 'desc' => ['fr' => 'Demandes de donnees, export, suppression et suivi.', 'en' => 'Data requests, export, erasure and follow-up.'], 'permission' => 'admin.access'],
    ];

    $catalog[] = [
        'route' => 'admin_classifieds',
        'title' => ['fr' => 'Petites annonces', 'en' => 'Classifieds'],
        'desc' => ['fr' => 'Modération des annonces membres.', 'en' => 'Moderate member classifieds.'],
        'module' => 'classifieds',
        'permission' => 'ads.moderate',
    ];

    $allSupportedLocales = supported_locales();
    foreach ($catalog as &$card) {
        foreach (['title', 'desc', 'audience', 'icon'] as $field) {
            if (!isset($card[$field]) || !is_array($card[$field])) {
                continue;
            }
            $localized = (array) $card[$field];
            foreach ($allSupportedLocales as $localeCode) {
                if (!isset($localized[$localeCode]) || trim((string) $localized[$localeCode]) === '') {
                    $localized[$localeCode] = (string) ($localized['en'] ?? $localized['fr'] ?? '');
                }
            }
            $card[$field] = $localized;
        }
    }
    unset($card);

    return $catalog;
}
