<?php
declare(strict_types=1);
require_login();
$locale=current_locale();
$titleMap=['fr'=>'Band planning ON2','en'=>'ON2 band plan','de'=>'ON2-Bandplan','nl'=>'ON2-bandplan'];$title=$titleMap[$locale] ?? $titleMap['fr'];
$h=['fr'=>['band'=>'Bande','freq'=>'Fréquences (MHz)','modes'=>'Modes','pwr'=>'Puissance max*','notes'=>'Notes'],'en'=>['band'=>'Band','freq'=>'Frequencies (MHz)','modes'=>'Modes','pwr'=>'Max power*','notes'=>'Notes'],'de'=>['band'=>'Band','freq'=>'Frequenzen (MHz)','modes'=>'Betriebsarten','pwr'=>'Max. Leistung*','notes'=>'Hinweise'],'nl'=>['band'=>'Band','freq'=>'Frequenties (MHz)','modes'=>'Modes','pwr'=>'Max vermogen*','notes'=>'Notities']][$locale] ?? ['band'=>'Bande','freq'=>'Fréquences (MHz)','modes'=>'Modes','pwr'=>'Puissance max*','notes'=>'Notes'];
$rows=[['80 m','3.500–3.800','CW/SSB/Data',['fr'=>'Découpage IARU à respecter.','en'=>'Follow IARU segmentation.','de'=>'IARU-Segmentierung beachten.','nl'=>'IARU-segmentering volgen.'],'100 W PEP'],['40 m','7.000–7.200','CW/SSB/Data',['fr'=>'Trafic dense en concours.','en'=>'Heavy contest activity.','de'=>'Hohe Contest-Aktivität.','nl'=>'Druk contestverkeer.'],'100 W PEP'],['20 m','14.000–14.350','CW/SSB/Data',['fr'=>'14.074 MHz FT8.','en'=>'14.074 MHz FT8.','de'=>'14,074 MHz FT8.','nl'=>'14.074 MHz FT8.'],'100 W PEP'],['2 m','144.000–146.000','FM/SSB/CW',['fr'=>'Simplex d’appel 145.500.','en'=>'Simplex calling 145.500.','de'=>'Simplex-Ruf 145,500.','nl'=>'Simplex-oproep 145.500.'],'50 W']];
ob_start(); ?>
<section class="card"><h1><?= e($title) ?></h1><p class="help">IBPT/BIPT: <a href="https://www.ibpt.be/file/cc73d96153bbd5448a56f19d925d05b1379c7f21/1891ad4029fa18396c037433ed4c2a063854f1b0/freq-fr.pdf?name=Freq-FR.pdf&type=application%2Fpdf" target="_blank" rel="noopener noreferrer">Freq‑FR.pdf</a></p><div class="table-wrap mt-3"><table><thead><tr><th><?=e($h['band'])?></th><th><?=e($h['freq'])?></th><th><?=e($h['modes'])?></th><th><?=e($h['pwr'])?></th><th><?=e($h['notes'])?></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=e($r[0])?></td><td><?=e($r[1])?></td><td><?=e($r[2])?></td><td><?=e($r[4])?></td><td><?=e($r[3][$locale] ?? $r[3]['fr'])?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php echo render_layout((string)ob_get_clean(),$title); ?>
