<?php
declare(strict_types=1);
require_login();
$locale=current_locale();
$titleMap=['fr'=>'Band planning ON3','en'=>'ON3 band plan','de'=>'ON3-Bandplan','nl'=>'ON3-bandplan','es'=>'Plan de banda ON3','it'=>'Piano di banda ON3','pt'=>'Plano de banda ON3','ar'=>'خطة نطاق ON3','hi'=>'ON3 बैंड प्लान','ja'=>'ON3 バンドプラン','zh'=>'ON3 频段规划','bn'=>'ON3 ব্যান্ড প্ল্যান','ru'=>'План диапазонов ON3','id'=>'Rencana band ON3'];
$title=i18n_localized_value($titleMap,$locale,'fr');
$hMap=['fr'=>['band'=>'Bande','freq'=>'Fréquences (MHz)','modes'=>'Modes','pwr'=>'Puissance max*','notes'=>'Notes'],'en'=>['band'=>'Band','freq'=>'Frequencies (MHz)','modes'=>'Modes','pwr'=>'Max power*','notes'=>'Notes'],'de'=>['band'=>'Band','freq'=>'Frequenzen (MHz)','modes'=>'Betriebsarten','pwr'=>'Max. Leistung*','notes'=>'Hinweise'],'nl'=>['band'=>'Band','freq'=>'Frequenties (MHz)','modes'=>'Modes','pwr'=>'Max vermogen*','notes'=>'Notities'],'es'=>['band'=>'Banda','freq'=>'Frecuencias (MHz)','modes'=>'Modos','pwr'=>'Potencia máx.*','notes'=>'Notas'],'it'=>['band'=>'Banda','freq'=>'Frequenze (MHz)','modes'=>'Modi','pwr'=>'Potenza max*','notes'=>'Note'],'pt'=>['band'=>'Banda','freq'=>'Frequências (MHz)','modes'=>'Modos','pwr'=>'Potência máx.*','notes'=>'Notas'],'ar'=>['band'=>'النطاق','freq'=>'الترددات (MHz)','modes'=>'الأنماط','pwr'=>'القدرة القصوى*','notes'=>'ملاحظات'],'hi'=>['band'=>'बैंड','freq'=>'आवृत्तियाँ (MHz)','modes'=>'मोड','pwr'=>'अधिकतम शक्ति*','notes'=>'टिप्पणियाँ'],'ja'=>['band'=>'バンド','freq'=>'周波数 (MHz)','modes'=>'モード','pwr'=>'最大出力*','notes'=>'備考'],'zh'=>['band'=>'波段','freq'=>'频率 (MHz)','modes'=>'模式','pwr'=>'最大功率*','notes'=>'备注'],'bn'=>['band'=>'ব্যান্ড','freq'=>'ফ্রিকোয়েন্সি (MHz)','modes'=>'মোড','pwr'=>'সর্বোচ্চ শক্তি*','notes'=>'নোট'],'ru'=>['band'=>'Диапазон','freq'=>'Частоты (MHz)','modes'=>'Режимы','pwr'=>'Макс. мощность*','notes'=>'Примечания'],'id'=>['band'=>'Band','freq'=>'Frekuensi (MHz)','modes'=>'Mode','pwr'=>'Daya maks*','notes'=>'Catatan']];$h=[];foreach(array_keys($hMap['fr']) as $key){$pool=[];foreach($hMap as $lang=>$items){$pool[$lang]=(string)($items[$key] ?? '');}$h[$key]=i18n_localized_value($pool,$locale,'fr');};
$rows=[
['80 m','3.500–3.600','CW/SSB',['fr'=>'Segment ON3 limité selon autorisation.','en'=>'ON3 limited segment per authorization.','de'=>'ON3-Teilbereich gemäß Genehmigung.','nl'=>'ON3-beperkt segment volgens vergunning.','es'=>'Segmento ON3 limitado según autorización.','it'=>'Segmento ON3 limitato secondo autorizzazione.','pt'=>'Segmento ON3 limitado conforme autorização.','ar'=>'جزء ON3 محدود حسب الترخيص.','hi'=>'अनुमति के अनुसार ON3 सीमित खंड।','ja'=>'認可に応じた ON3 制限セグメント。','zh'=>'根据授权限制的 ON3 频段。','bn'=>'অনুমোদন অনুযায়ী ON3 সীমিত সেগমেন্ট।','ru'=>'Ограниченный сегмент ON3 согласно разрешению.','id'=>'Segmen ON3 terbatas sesuai izin.'],'10 W PEP'],
['40 m','7.000–7.100','CW/SSB',['fr'=>'Utilisation partielle selon réglementation.','en'=>'Partial use per regulation.','de'=>'Teilnutzung gemäß Vorschriften.','nl'=>'Gedeeltelijk gebruik volgens regelgeving.','es'=>'Uso parcial según normativa.','it'=>'Uso parziale secondo normativa.','pt'=>'Uso parcial conforme regulamento.','ar'=>'استخدام جزئي وفق اللوائح.','hi'=>'नियमों के अनुसार आंशिक उपयोग।','ja'=>'規制に基づく部分利用。','zh'=>'根据法规部分使用。','bn'=>'বিধি অনুযায়ী আংশিক ব্যবহার।','ru'=>'Частичное использование в соответствии с правилами.','id'=>'Penggunaan sebagian sesuai regulasi.'],'10 W PEP'],
['15 m','21.100–21.200','SSB/Data',['fr'=>'Ouverture surtout diurne.','en'=>'Mostly daytime openings.','de'=>'Öffnungen meist tagsüber.','nl'=>'Openingen vooral overdag.','es'=>'Aperturas principalmente diurnas.','it'=>'Aperture soprattutto diurne.','pt'=>'Aberturas sobretudo diurnas.','ar'=>'فتحات غالبًا نهارية.','hi'=>'अधिकतर दिन के समय खुलाव।','ja'=>'主に日中にオープン。','zh'=>'主要在白天开放。','bn'=>'বেশিরভাগই দিনের বেলায় খোলে।','ru'=>'Открытия в основном днём.','id'=>'Kondisi terbuka umumnya pada siang hari.'],'10 W PEP'],
['10 m','28.000–29.700','CW/SSB/FM/Data',['fr'=>'Sous-bandes selon plan IARU.','en'=>'Sub-bands per IARU plan.','de'=>'Teilbänder nach IARU-Plan.','nl'=>'Subbanden volgens IARU-plan.','es'=>'Subbandas según el plan IARU.','it'=>'Sottobande secondo piano IARU.','pt'=>'Sub-bandas conforme o plano IARU.','ar'=>'نطاقات فرعية وفق خطة IARU.','hi'=>'IARU योजना के अनुसार उप-बैंड।','ja'=>'IARU 計画に基づくサブバンド。','zh'=>'按 IARU 计划划分的子频段。','bn'=>'IARU পরিকল্পনা অনুযায়ী সাব-ব্যান্ড।','ru'=>'Поддиапазоны по плану IARU.','id'=>'Sub-band sesuai rencana IARU.'],'10 W PEP'],
['2 m','144.000–146.000','FM/SSB/CW',['fr'=>'145.500 MHz appel simplex.','en'=>'145.500 MHz simplex calling.','de'=>'145,500 MHz Simplex-Anruf.','nl'=>'145.500 MHz simplex-oproep.','es'=>'145.500 MHz llamada simplex.','it'=>'145.500 MHz chiamata simplex.','pt'=>'145.500 MHz chamada simplex.','ar'=>'نداء سيمبلكس على 145.500 MHz.','hi'=>'145.500 MHz सिंप्लेक्स कॉलिंग।','ja'=>'145.500 MHz シンプレックス呼出。','zh'=>'145.500 MHz 单工呼叫。','bn'=>'145.500 MHz সিমপ্লেক্স কলিং।','ru'=>'Симплекс-вызов на 145.500 МГц.','id'=>'Panggilan simplex pada 145.500 MHz.'],'10 W PEP'],
['70 cm','430.000–440.000','FM/Relais/numérique',['fr'=>'Respecter le plan relais local.','en'=>'Follow local repeater plan.','de'=>'Lokalen Relaisplan beachten.','nl'=>'Volg het lokale relaisplan.','es'=>'Respetar el plan local de repetidores.','it'=>'Seguire il piano locale dei ripetitori.','pt'=>'Respeitar o plano local de repetidores.','ar'=>'اتبع خطة المكررات المحلية.','hi'=>'स्थानीय रिपीटर योजना का पालन करें।','ja'=>'地域リピータ計画に従ってください。','zh'=>'请遵循本地中继台规划。','bn'=>'স্থানীয় রিপিটার পরিকল্পনা অনুসরণ করুন।','ru'=>'Следуйте местному плану ретрансляторов.','id'=>'Ikuti rencana repeater lokal.'],'10 W PEP'],
['23 cm','1240–1300','FM/SSB/Data',['fr'=>'Portions partagées, filtrage conseillé.','en'=>'Shared segments, filtering recommended.','de'=>'Geteilte Segmente, Filter empfohlen.','nl'=>'Gedeelde segmenten, filtering aanbevolen.','es'=>'Segmentos compartidos, filtrado recomendado.','it'=>'Segmenti condivisi, filtraggio consigliato.','pt'=>'Segmentos partilhados, filtragem recomendada.','ar'=>'أجزاء مشتركة، يُنصح بالترشيح.','hi'=>'साझा खंड, फ़िल्टरिंग अनुशंसित।','ja'=>'共有セグメントのため、フィルタ推奨。','zh'=>'共享频段，建议进行滤波。','bn'=>'শেয়ারড সেগমেন্ট, ফিল্টারিং সুপারিশকৃত।','ru'=>'Общие сегменты, рекомендуется фильтрация.','id'=>'Segmen berbagi, disarankan menggunakan filter.'],'10 W PEP'],
];
ob_start(); ?>
<section class="card"><h1><?= e($title) ?></h1><p class="help">IBPT/BIPT: <a href="https://www.ibpt.be/file/cc73d96153bbd5448a56f19d925d05b1379c7f21/1891ad4029fa18396c037433ed4c2a063854f1b0/freq-fr.pdf?name=Freq-FR.pdf&type=application%2Fpdf" target="_blank" rel="noopener noreferrer">Freq‑FR.pdf</a></p><div class="table-wrap mt-3"><table><thead><tr><th><?=e($h['band'])?></th><th><?=e($h['freq'])?></th><th><?=e($h['modes'])?></th><th><?=e($h['pwr'])?></th><th><?=e($h['notes'])?></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=e($r[0])?></td><td><?=e($r[1])?></td><td><?=e($r[2])?></td><td><?=e($r[4])?></td><td><?=e(i18n_localized_value($r[3],$locale,'fr'))?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php echo render_layout((string)ob_get_clean(),$title); ?>
