<?php
declare(strict_types=1);
require_login();
$locale = current_locale();
$titles = ['fr'=>'Code Q radioamateur (version exhaustive)','en'=>'Amateur radio Q-code (extended)','de'=>'Q-Code Funkamateur (erweitert)','nl'=>'Q-code radioamateur (uitgebreid)','es'=>'Código Q de radioaficionado (ampliado)','it'=>'Codice Q radioamatoriale (esteso)','pt'=>'Código Q de radioamador (alargado)','ar'=>'رموز Q لهواة الراديو (نسخة موسعة)','hi'=>'एमेच्योर रेडियो Q-कोड (विस्तारित)','ja'=>'アマチュア無線Qコード（拡張版）','zh'=>'业余无线电Q代码（扩展版）','bn'=>'অ্যামেচার রেডিও Q-কোড (বিস্তৃত)','ru'=>'Q-код радиолюбителя (расширенная версия)','id'=>'Kode Q radio amatir (versi lengkap)'];
$title = i18n_localized_value($titles, $locale, 'fr');
$meaningLabels = ['fr'=>'Signification','en'=>'Meaning','de'=>'Bedeutung','nl'=>'Betekenis','es'=>'Significado','it'=>'Significato','pt'=>'Significado','ar'=>'المعنى','hi'=>'अर्थ','ja'=>'意味','zh'=>'含义','bn'=>'অর্থ','ru'=>'Значение','id'=>'Arti'];
$meaningLabel = i18n_localized_value($meaningLabels, $locale, 'fr');
$qRows = [
['QRA','Nom de la station'],['QRB','Distance entre stations'],['QRG','Fréquence exacte'],['QRH','Variation de fréquence'],['QRI','Tonalité du signal'],['QRJ','Nombre de signaux reçus'],['QRK','Lisibilité du signal'],['QRL','Fréquence occupée'],['QRM','Interférences'],['QRN','Bruit atmosphérique'],['QRO','Augmenter la puissance'],['QRP','Réduire la puissance'],['QRQ','Émettre plus vite'],['QRR','Prêt pour trafic automatique'],['QRS','Émettre plus lentement'],['QRT','Cesser d’émettre'],['QRU','Avez-vous quelque chose pour moi ?'],['QRV','Êtes-vous prêt ?'],['QRW','Prévenez ... de m’appeler'],['QRX','Rappeler à ...'],['QRY','Quel est mon tour ?'],['QRZ','Qui m’appelle ?'],
['QSA','Force du signal'],['QSB','Variation du signal'],['QSD','Manipulation défectueuse'],['QSE','Décalage estimé de fréquence'],['QSF','Dois-je transmettre un message ?'],['QSG','Émettre x messages à la fois'],['QSH','Puis-je répéter ?'],['QSI','Je ne peux interrompre'],['QSJ','Montant à payer'],['QSK','Écoute entre signaux'],['QSL','Accusé de réception'],['QSM','Répéter dernier message'],['QSN','M’avez-vous entendu ?'],['QSO','Communication entre stations'],['QSP','Relayer un message'],['QSQ','Médecin à bord ?'],['QSR','Répéter sur fréquence'],['QSS','Quelle fréquence de travail ?'],['QST','Message général'],['QSU','Émettre sur fréquence actuelle'],['QSV','Série de V'],['QSW','Émettre sur cette fréquence'],['QSX','Écouter sur autre fréquence'],['QSY','Changer de fréquence'],['QSZ','Répéter chaque mot 2x'],['QTA','Annuler message'],['QTB','Compter les mots ?'],['QTC','Messages à transmettre'],['QTD','Jusqu’où va le trafic ?'],['QTE','Relèvement vrai'],['QTF','Position à partir relèvements'],['QTG','Émettre deux traits'],['QTH','Position géographique'],['QTI','Cap vrai'],['QTJ','Vitesse vraie'],['QTK','Vitesse appareil'],['QTL','Cap vrai à suivre'],['QTM','Vitesse indiquée'],['QTN','Départ à ...'],['QTO','Sortie de port à ...'],['QTP','Entrée de port à ...'],['QTQ','Communiquer via code international'],['QTR','Heure exacte'],['QTS','Conserver écoute sur ...'],['QTT','Signal d’identification'],['QTU','Heures d’exploitation'],['QTV','Veille pour moi sur ...'],['QTW','État des survivants'],['QTX','Station ouverte pour trafic'],['QTY','Route vers ma position'],['QTZ','Continuer recherche'],
];
ob_start();
?>
<section class="card">
  <h1><?= e($title) ?></h1>
  <p class="help"><?php $introMap = ['fr'=>'Tableau étendu des Q-codes utilisés en radiocommunication (radioamateur et trafic général).','en'=>'Extended table of Q-codes used in radiocommunications (amateur and general traffic).','de'=>'Erweiterte Tabelle der Q-Codes im Funkverkehr (Amateurfunk und Allgemeinfunk).','nl'=>'Uitgebreide tabel van Q-codes gebruikt in radiocommunicatie (amateur en algemeen verkeer).','es'=>'Tabla ampliada de códigos Q usados en radiocomunicaciones (radioafición y tráfico general).','it'=>'Tabella estesa dei codici Q usati nelle radiocomunicazioni (radioamatori e traffico generale).','pt'=>'Tabela alargada de códigos Q usados em radiocomunicações (radioamador e tráfego geral).','ar'=>'جدول موسّع لرموز Q المستخدمة في الاتصالات الراديوية (الهواة وحركة الاتصالات العامة).','hi'=>'रेडियो संचार (शौकिया और सामान्य ट्रैफ़िक) में उपयोग होने वाले Q-कोड्स की विस्तृत तालिका।','ja'=>'無線通信（アマチュアおよび一般通信）で使われるQコードの拡張表です。','zh'=>'用于无线电通信（业余与一般通信）的Q代码扩展表。','bn'=>'রেডিও যোগাযোগে (অ্যামেচার ও সাধারণ ট্রাফিক) ব্যবহৃত Q-কোডগুলোর বিস্তৃত তালিকা।','ru'=>'Расширенная таблица Q-кодов, используемых в радиосвязи (радиолюбительской и общей).','id'=>'Tabel lengkap kode Q yang digunakan dalam radiokomunikasi (amatir dan lalu lintas umum).']; ?><?= e(i18n_localized_value($introMap, $locale, 'fr')) ?></p>
  <div class="table-wrap mt-3"><table><thead><tr><th>Code Q</th><th><?= e($meaningLabel) ?></th></tr></thead><tbody>
  <?php foreach ($qRows as $row): ?>
    <tr><td><?= e($row[0]) ?></td><td><?= e($row[1]) ?></td></tr>
  <?php endforeach; ?>
  </tbody></table></div>
</section>
<?php echo render_layout((string) ob_get_clean(), $title); ?>
