<?php
declare(strict_types=1);

$locale = current_locale();
$i18n = [
    'fr' => ['meta_title' => 'Notre relais ONØCRD', 'meta_desc' => 'Informations techniques et accès EchoLink du relais ONØCRD.', 'title' => 'Notre relais', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Oui / Oui (enc./dec.)', 'callsign' => 'Indicatif', 'channel' => 'Canal', 'mode' => 'Mode', 'mode_value' => 'Mode Répétiteur FM + EchoLink', 'input' => "Fréquence d'entrée ( TX )", 'output' => 'Fréquence de sortie ( RX )', 'shift' => 'Décalage', 'subtone' => 'Sous-ton CTCSS', 'polarization' => 'Polarisation', 'polarization_value' => 'Verticale 6,5 dBi', 'locator' => 'Localisateur', 'locator_value' => 'JO20LI', 'location' => 'Localisation', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Puissance', 'power_value' => '25 W', 'altitude' => 'Altitude', 'altitude_value' => '314 m', 'tx' => 'Entrée ( TX )', 'rx' => 'Sortie ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Accès Echolink mis en place pour nos amis hors de portée du relais de Durnal.', 'p2' => 'Merci de privilégier le VHF si vous êtes à portée du relais. Balise vocale toutes les 15 min.', 'p3' => 'Le Relais SVXlink installé est l’implémentation d’un lien SVXLink (Echolink) avec un Relais FM existant. Ici: ONØCRD – Sysop ON4DL – Suppléant ON5GB. « svxlink » est un système de service vocal à usage général pour l\'utilisation de la radio « amateur » .', 'p4' => 'Avec la collaboration de ON4LS est né depuis ce 18/03/2021 un accès Echolink sur ONØCRD. Par ceci nous ouvrons une porte à nos amis afin de garder contact avec les OM’s de la zone couverte par le relais.'],
    'en' => ['meta_title' => 'Our ONØCRD repeater', 'meta_desc' => 'Technical information and EchoLink access for ONØCRD repeater.', 'title' => 'Our repeater', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144.975', 'output_value' => '145.575', 'shift_value' => '0.6', 'subtone_value' => '131.8', 'subtone_status_value' => 'Yes / Yes (enc./dec.)', 'callsign' => 'Callsign', 'channel' => 'Channel', 'mode' => 'Mode', 'mode_value' => 'FM repeater mode + EchoLink', 'input' => 'Input frequency ( TX )', 'output' => 'Output frequency ( RX )', 'shift' => 'Shift', 'subtone' => 'CTCSS subtone', 'polarization' => 'Polarization', 'polarization_value' => 'Vertical 6.5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Location', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Power', 'power_value' => '25 W', 'altitude' => 'Altitude', 'altitude_value' => '314 m', 'tx' => 'Input ( TX )', 'rx' => 'Output ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Echolink access is available for friends outside Durnal repeater coverage.', 'p2' => 'Please prefer VHF if you are within repeater coverage. Voice beacon every 15 minutes.', 'p3' => 'The installed SVXlink repeater is an SVXLink (Echolink) link with an existing FM repeater. Here: ONØCRD – Sysop ON4DL – Deputy ON5GB. “svxlink” is a general-purpose voice service system for amateur radio usage.', 'p4' => 'With ON4LS collaboration, EchoLink access on ONØCRD has been available since 18/03/2021. This opens a gateway to keep contact with OMs in the repeater coverage area.'],
    'de' => ['meta_title' => 'Unser ONØCRD-Relais', 'meta_desc' => 'Technische Informationen und EchoLink-Zugang für das ONØCRD-Relais.', 'title' => 'Unser Relais', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Ja / Ja (enc./dec.)', 'callsign' => 'Rufzeichen', 'channel' => 'Kanal', 'mode' => 'Modus', 'mode_value' => 'FM-Relaismodus + EchoLink', 'input' => 'Eingangsfrequenz ( TX )', 'output' => 'Ausgangsfrequenz ( RX )', 'shift' => 'Ablage', 'subtone' => 'CTCSS-Subton', 'polarization' => 'Polarisation', 'polarization_value' => 'Vertikal 6,5 dBi', 'locator' => 'Lokator', 'locator_value' => 'JO20LI', 'location' => 'Standort', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Leistung', 'power_value' => '25 W', 'altitude' => 'Höhe', 'altitude_value' => '314 m', 'tx' => 'Eingang ( TX )', 'rx' => 'Ausgang ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Echolink-Zugang wurde für Freunde außerhalb der Reichweite des Durnal-Relais eingerichtet.', 'p2' => 'Bitte bevorzugen Sie VHF, wenn Sie in Reichweite des Relais sind. Sprachbake alle 15 Minuten.', 'p3' => 'Das installierte SVXlink-Relais ist eine SVXLink-(Echolink)-Anbindung an ein bestehendes FM-Relais. Hier: ONØCRD – Sysop ON4DL – Stellvertreter ON5GB. „svxlink“ ist ein allgemeines Sprachdienstsystem für die Amateurfunknutzung.', 'p4' => 'In Zusammenarbeit mit ON4LS wurde seit dem 18.03.2021 ein Echolink-Zugang auf ONØCRD eingerichtet. So halten wir den Kontakt mit OMs im Abdeckungsbereich des Relais.'],
    'es' => ['meta_title' => 'Nuestro repetidor ONØCRD', 'meta_desc' => 'Información técnica y acceso EchoLink del repetidor ONØCRD.', 'title' => 'Nuestro repetidor', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Sí / Sí (enc./dec.)', 'callsign' => 'Indicativo', 'channel' => 'Canal', 'mode' => 'Modo', 'mode_value' => 'Modo repetidor FM + EchoLink', 'input' => 'Frecuencia de entrada ( TX )', 'output' => 'Frecuencia de salida ( RX )', 'shift' => 'Desplazamiento', 'subtone' => 'Subtono CTCSS', 'polarization' => 'Polarización', 'polarization_value' => 'Vertical 6,5 dBi', 'locator' => 'Localizador', 'locator_value' => 'JO20LI', 'location' => 'Ubicación', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Potencia', 'power_value' => '25 W', 'altitude' => 'Altitud', 'altitude_value' => '314 m', 'tx' => 'Entrada ( TX )', 'rx' => 'Salida ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Acceso Echolink disponible para amigos fuera de la cobertura del repetidor de Durnal.', 'p2' => 'Priorice VHF si está dentro de cobertura. Baliza de voz cada 15 minutos.', 'p3' => 'El repetidor SVXlink instalado es una integración SVXLink (Echolink) con un repetidor FM existente. Aquí: ONØCRD – Sysop ON4DL – Suplente ON5GB.', 'p4' => 'Con la colaboración de ON4LS, el acceso Echolink en ONØCRD está activo desde el 18/03/2021.'],
    'it' => ['meta_title' => 'Il nostro ripetitore ONØCRD', 'meta_desc' => 'Informazioni tecniche e accesso EchoLink del ripetitore ONØCRD.', 'title' => 'Il nostro ripetitore', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Sì / Sì (enc./dec.)', 'callsign' => 'Nominativo', 'channel' => 'Canale', 'mode' => 'Modo', 'mode_value' => 'Modo ripetitore FM + EchoLink', 'input' => 'Frequenza di ingresso ( TX )', 'output' => 'Frequenza di uscita ( RX )', 'shift' => 'Shift', 'subtone' => 'Subtono CTCSS', 'polarization' => 'Polarizzazione', 'polarization_value' => 'Verticale 6,5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Posizione', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Potenza', 'power_value' => '25 W', 'altitude' => 'Altitudine', 'altitude_value' => '314 m', 'tx' => 'Ingresso ( TX )', 'rx' => 'Uscita ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Accesso Echolink disponibile per amici fuori copertura del ripetitore di Durnal.', 'p2' => 'Privilegiare la VHF se in copertura. Faro vocale ogni 15 minuti.', 'p3' => 'Il ripetitore SVXlink installato è un collegamento SVXLink (Echolink) con un ripetitore FM esistente. Qui: ONØCRD – Sysop ON4DL – Supplente ON5GB.', 'p4' => 'Con la collaborazione di ON4LS, l\'accesso Echolink su ONØCRD è attivo dal 18/03/2021.'],
    'pt' => ['meta_title' => 'O nosso repetidor ONØCRD', 'meta_desc' => 'Informações técnicas e acesso EchoLink do repetidor ONØCRD.', 'title' => 'O nosso repetidor', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Sim / Sim (enc./dec.)', 'callsign' => 'Indicativo', 'channel' => 'Canal', 'mode' => 'Modo', 'mode_value' => 'Modo repetidor FM + EchoLink', 'input' => 'Frequência de entrada ( TX )', 'output' => 'Frequência de saída ( RX )', 'shift' => 'Desvio', 'subtone' => 'Subtom CTCSS', 'polarization' => 'Polarização', 'polarization_value' => 'Vertical 6,5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Localização', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Potência', 'power_value' => '25 W', 'altitude' => 'Altitude', 'altitude_value' => '314 m', 'tx' => 'Entrada ( TX )', 'rx' => 'Saída ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Acesso Echolink disponível para amigos fora da cobertura do repetidor de Durnal.', 'p2' => 'Prefira VHF se estiver na cobertura. Baliza de voz a cada 15 minutos.', 'p3' => 'O repetidor SVXlink instalado é uma ligação SVXLink (Echolink) com um repetidor FM existente. Aqui: ONØCRD – Sysop ON4DL – Suplente ON5GB.', 'p4' => 'Com a colaboração de ON4LS, o acesso Echolink no ONØCRD está ativo desde 18/03/2021.'],
    'nl' => ['meta_title' => 'Onze ONØCRD-repeater', 'meta_desc' => 'Technische informatie en EchoLink-toegang voor de ONØCRD-repeater.', 'title' => 'Onze repeater', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Ja / Ja (enc./dec.)', 'callsign' => 'Roepnaam', 'channel' => 'Kanaal', 'mode' => 'Modus', 'mode_value' => 'FM-repeatermodus + EchoLink', 'input' => 'Ingangsfrequentie ( TX )', 'output' => 'Uitgangsfrequentie ( RX )', 'shift' => 'Shift', 'subtone' => 'CTCSS-subtoon', 'polarization' => 'Polarisatie', 'polarization_value' => 'Verticaal 6,5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Locatie', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Vermogen', 'power_value' => '25 W', 'altitude' => 'Hoogte', 'altitude_value' => '314 m', 'tx' => 'Ingang ( TX )', 'rx' => 'Uitgang ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Echolink-toegang is voorzien voor vrienden buiten bereik van de Durnal-repeater.', 'p2' => 'Gebruik bij voorkeur VHF als je binnen bereik van de repeater bent. Spraakbaken elke 15 minuten.', 'p3' => 'De geïnstalleerde SVXlink-repeater is een SVXLink(Echolink)-koppeling met een bestaande FM-repeater. Hier: ONØCRD – Sysop ON4DL – Plaatsvervanger ON5GB. “svxlink” is een algemeen spraakservicesysteem voor amateurradiogebruik.', 'p4' => 'Met medewerking van ON4LS is sinds 18/03/2021 Echolink-toegang op ONØCRD beschikbaar. Zo houden we contact met OMs in het dekkingsgebied van de repeater.'],
];
$i18n = i18n_expand_supported_locales($i18n);
$t = static function (string $key) use ($locale, $i18n): string {
    return (string) (($i18n[$locale] ?? $i18n['fr'])[$key] ?? $key);
};

set_page_meta([
    'title' => $t('meta_title'),
    'description' => $t('meta_desc'),
    'schema_type' => 'WebPage',
]);

ob_start();
?>
<section class="card max-w-5xl mx-auto">
    <h1 class="text-3xl font-bold text-slate-900 text-center"><?= e($t('title')) ?></h1>
    <div class="mt-6 overflow-x-auto">
        <table class="w-full min-w-[720px] border border-slate-200 rounded-xl overflow-hidden text-sm">
            <tbody>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('callsign')) ?></th><td class="px-4 py-3"><?= e($t('callsign_value')) ?></td><td class="px-4 py-3"><?= e($t('tx')) ?></td><td class="px-4 py-3"><?= e($t('rx')) ?></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('channel')) ?></th><td class="px-4 py-3"><?= e($t('channel_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('mode')) ?></th><td class="px-4 py-3"><?= e($t('mode_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('input')) ?></th><td class="px-4 py-3"><?= e($t('input_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_mhz')) ?></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('output')) ?></th><td class="px-4 py-3"><?= e($t('output_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_mhz')) ?></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('shift')) ?></th><td class="px-4 py-3"><?= e($t('shift_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_mhz')) ?></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('subtone')) ?></th><td class="px-4 py-3"><?= e($t('subtone_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_hz')) ?></td><td class="px-4 py-3"><?= e($t('subtone_status_value')) ?></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('polarization')) ?></th><td class="px-4 py-3"><?= e($t('polarization_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('locator')) ?></th><td class="px-4 py-3"><?= e($t('locator_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('location')) ?></th><td class="px-4 py-3"><?= e($t('location_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('power')) ?></th><td class="px-4 py-3"><?= e($t('power_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('altitude')) ?></th><td class="px-4 py-3"><?= e($t('altitude_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            </tbody>
        </table>
    </div>

    <div class="mt-6 space-y-4 text-slate-700">
        <p><?= e($t('p1')) ?></p>
        <p><?= e($t('p2')) ?></p>
        <p><?= e($t('p3')) ?></p>
        <p><?= e($t('p4')) ?></p>
    </div>
</section>
<?php
echo render_layout((string) ob_get_clean(), $t('title'));
