<?php
declare(strict_types=1);

$locale = current_locale();
$i18n = [
    'fr' => ['meta_title' => 'Notre relais ONØCRD', 'meta_desc' => 'Informations techniques et accès EchoLink du relais ONØCRD.', 'title' => 'Notre relais', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Oui / Oui (enc./dec.)', 'callsign' => 'Indicatif', 'channel' => 'Canal', 'mode' => 'Mode', 'mode_value' => 'Mode Répétiteur FM + EchoLink', 'input' => "Fréquence d'entrée ( TX )", 'output' => 'Fréquence de sortie ( RX )', 'shift' => 'Décalage', 'subtone' => 'Sous-ton CTCSS', 'polarization' => 'Polarisation', 'polarization_value' => 'Verticale 6,5 dBi', 'locator' => 'Localisateur', 'locator_value' => 'JO20LI', 'location' => 'Localisation', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Puissance', 'power_value' => '25 W', 'altitude' => 'Altitude', 'altitude_value' => '314 m', 'tx' => 'Entrée ( TX )', 'rx' => 'Sortie ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Accès Echolink mis en place pour nos amis hors de portée du relais de Durnal.', 'p2' => 'Merci de privilégier le VHF si vous êtes à portée du relais. Balise vocale toutes les 15 min.', 'p3' => 'Le Relais SVXlink installé est l’implémentation d’un lien SVXLink (Echolink) avec un Relais FM existant. Ici: ONØCRD – Sysop ON4DL – Suppléant ON5GB. « svxlink » est un système de service vocal à usage général pour l\'utilisation de la radio « amateur » .', 'p4' => 'Avec la collaboration de ON4LS est né depuis ce 18/03/2021 un accès Echolink sur ONØCRD. Par ceci nous ouvrons une porte à nos amis afin de garder contact avec les OM’s de la zone couverte par le relais.'],
    'en' => ['meta_title' => 'Our ONØCRD repeater', 'meta_desc' => 'Technical information and EchoLink access for ONØCRD repeater.', 'title' => 'Our repeater', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144.975', 'output_value' => '145.575', 'shift_value' => '0.6', 'subtone_value' => '131.8', 'subtone_status_value' => 'Yes / Yes (enc./dec.)', 'callsign' => 'Callsign', 'channel' => 'Channel', 'mode' => 'Mode', 'mode_value' => 'FM repeater mode + EchoLink', 'input' => 'Input frequency ( TX )', 'output' => 'Output frequency ( RX )', 'shift' => 'Shift', 'subtone' => 'CTCSS subtone', 'polarization' => 'Polarization', 'polarization_value' => 'Vertical 6.5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Location', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Power', 'power_value' => '25 W', 'altitude' => 'Altitude', 'altitude_value' => '314 m', 'tx' => 'Input ( TX )', 'rx' => 'Output ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Echolink access is available for friends outside Durnal repeater coverage.', 'p2' => 'Please prefer VHF if you are within repeater coverage. Voice beacon every 15 minutes.', 'p3' => 'The installed SVXlink repeater is an SVXLink (Echolink) link with an existing FM repeater. Here: ONØCRD – Sysop ON4DL – Deputy ON5GB. “svxlink” is a general-purpose voice service system for amateur radio usage.', 'p4' => 'With ON4LS collaboration, EchoLink access on ONØCRD has been available since 18/03/2021. This opens a gateway to keep contact with OMs in the repeater coverage area.'],
    'de' => ['meta_title' => 'Unser ONØCRD-Relais', 'meta_desc' => 'Technische Informationen und EchoLink-Zugang für das ONØCRD-Relais.', 'title' => 'Unser Relais', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Ja / Ja (enc./dec.)', 'callsign' => 'Rufzeichen', 'channel' => 'Kanal', 'mode' => 'Modus', 'mode_value' => 'FM-Relaismodus + EchoLink', 'input' => 'Eingangsfrequenz ( TX )', 'output' => 'Ausgangsfrequenz ( RX )', 'shift' => 'Ablage', 'subtone' => 'CTCSS-Subton', 'polarization' => 'Polarisation', 'polarization_value' => 'Vertikal 6,5 dBi', 'locator' => 'Lokator', 'locator_value' => 'JO20LI', 'location' => 'Standort', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Leistung', 'power_value' => '25 W', 'altitude' => 'Höhe', 'altitude_value' => '314 m', 'tx' => 'Eingang ( TX )', 'rx' => 'Ausgang ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Echolink-Zugang wurde für Freunde außerhalb der Reichweite des Durnal-Relais eingerichtet.', 'p2' => 'Bitte bevorzugen Sie VHF, wenn Sie in Reichweite des Relais sind. Sprachbake alle 15 Minuten.', 'p3' => 'Das installierte SVXlink-Relais ist eine SVXLink-(Echolink)-Anbindung an ein bestehendes FM-Relais. Hier: ONØCRD – Sysop ON4DL – Stellvertreter ON5GB. „svxlink“ ist ein allgemeines Sprachdienstsystem für die Amateurfunknutzung.', 'p4' => 'In Zusammenarbeit mit ON4LS wurde seit dem 18.03.2021 ein Echolink-Zugang auf ONØCRD eingerichtet. So halten wir den Kontakt mit OMs im Abdeckungsbereich des Relais.'],
    'es' => ['meta_title' => 'Nuestro repetidor ONØCRD', 'meta_desc' => 'Información técnica y acceso EchoLink del repetidor ONØCRD.', 'title' => 'Nuestro repetidor', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Sí / Sí (enc./dec.)', 'callsign' => 'Indicativo', 'channel' => 'Canal', 'mode' => 'Modo', 'mode_value' => 'Modo repetidor FM + EchoLink', 'input' => 'Frecuencia de entrada ( TX )', 'output' => 'Frecuencia de salida ( RX )', 'shift' => 'Desplazamiento', 'subtone' => 'Subtono CTCSS', 'polarization' => 'Polarización', 'polarization_value' => 'Vertical 6,5 dBi', 'locator' => 'Localizador', 'locator_value' => 'JO20LI', 'location' => 'Ubicación', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Potencia', 'power_value' => '25 W', 'altitude' => 'Altitud', 'altitude_value' => '314 m', 'tx' => 'Entrada ( TX )', 'rx' => 'Salida ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Acceso Echolink disponible para amigos fuera de la cobertura del repetidor de Durnal.', 'p2' => 'Priorice VHF si está dentro de cobertura. Baliza de voz cada 15 minutos.', 'p3' => 'El repetidor SVXlink instalado es una integración SVXLink (Echolink) con un repetidor FM existente. Aquí: ONØCRD – Sysop ON4DL – Suplente ON5GB.', 'p4' => 'Con la colaboración de ON4LS, el acceso Echolink en ONØCRD está activo desde el 18/03/2021.'],
    'it' => ['meta_title' => 'Il nostro ripetitore ONØCRD', 'meta_desc' => 'Informazioni tecniche e accesso EchoLink del ripetitore ONØCRD.', 'title' => 'Il nostro ripetitore', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Sì / Sì (enc./dec.)', 'callsign' => 'Nominativo', 'channel' => 'Canale', 'mode' => 'Modo', 'mode_value' => 'Modo ripetitore FM + EchoLink', 'input' => 'Frequenza di ingresso ( TX )', 'output' => 'Frequenza di uscita ( RX )', 'shift' => 'Shift', 'subtone' => 'Subtono CTCSS', 'polarization' => 'Polarizzazione', 'polarization_value' => 'Verticale 6,5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Posizione', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Potenza', 'power_value' => '25 W', 'altitude' => 'Altitudine', 'altitude_value' => '314 m', 'tx' => 'Ingresso ( TX )', 'rx' => 'Uscita ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Accesso Echolink disponibile per amici fuori copertura del ripetitore di Durnal.', 'p2' => 'Privilegiare la VHF se in copertura. Faro vocale ogni 15 minuti.', 'p3' => 'Il ripetitore SVXlink installato è un collegamento SVXLink (Echolink) con un ripetitore FM esistente. Qui: ONØCRD – Sysop ON4DL – Supplente ON5GB.', 'p4' => 'Con la collaborazione di ON4LS, l\'accesso Echolink su ONØCRD è attivo dal 18/03/2021.'],
    'pt' => ['meta_title' => 'O nosso repetidor ONØCRD', 'meta_desc' => 'Informações técnicas e acesso EchoLink do repetidor ONØCRD.', 'title' => 'O nosso repetidor', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Sim / Sim (enc./dec.)', 'callsign' => 'Indicativo', 'channel' => 'Canal', 'mode' => 'Modo', 'mode_value' => 'Modo repetidor FM + EchoLink', 'input' => 'Frequência de entrada ( TX )', 'output' => 'Frequência de saída ( RX )', 'shift' => 'Desvio', 'subtone' => 'Subtom CTCSS', 'polarization' => 'Polarização', 'polarization_value' => 'Vertical 6,5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Localização', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Potência', 'power_value' => '25 W', 'altitude' => 'Altitude', 'altitude_value' => '314 m', 'tx' => 'Entrada ( TX )', 'rx' => 'Saída ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Acesso Echolink disponível para amigos fora da cobertura do repetidor de Durnal.', 'p2' => 'Prefira VHF se estiver na cobertura. Baliza de voz a cada 15 minutos.', 'p3' => 'O repetidor SVXlink instalado é uma ligação SVXLink (Echolink) com um repetidor FM existente. Aqui: ONØCRD – Sysop ON4DL – Suplente ON5GB.', 'p4' => 'Com a colaboração de ON4LS, o acesso Echolink no ONØCRD está ativo desde 18/03/2021.'],
    'nl' => ['meta_title' => 'Onze ONØCRD-repeater', 'meta_desc' => 'Technische informatie en EchoLink-toegang voor de ONØCRD-repeater.', 'title' => 'Onze repeater', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Ja / Ja (enc./dec.)', 'callsign' => 'Roepnaam', 'channel' => 'Kanaal', 'mode' => 'Modus', 'mode_value' => 'FM-repeatermodus + EchoLink', 'input' => 'Ingangsfrequentie ( TX )', 'output' => 'Uitgangsfrequentie ( RX )', 'shift' => 'Shift', 'subtone' => 'CTCSS-subtoon', 'polarization' => 'Polarisatie', 'polarization_value' => 'Verticaal 6,5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Locatie', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Vermogen', 'power_value' => '25 W', 'altitude' => 'Hoogte', 'altitude_value' => '314 m', 'tx' => 'Ingang ( TX )', 'rx' => 'Uitgang ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Echolink-toegang is voorzien voor vrienden buiten bereik van de Durnal-repeater.', 'p2' => 'Gebruik bij voorkeur VHF als je binnen bereik van de repeater bent. Spraakbaken elke 15 minuten.', 'p3' => 'De geïnstalleerde SVXlink-repeater is een SVXLink(Echolink)-koppeling met een bestaande FM-repeater. Hier: ONØCRD – Sysop ON4DL – Plaatsvervanger ON5GB. “svxlink” is een algemeen spraakservicesysteem voor amateurradiogebruik.', 'p4' => 'Met medewerking van ON4LS is sinds 18/03/2021 Echolink-toegang op ONØCRD beschikbaar. Zo houden we contact met OMs in het dekkingsgebied van de repeater.'],

    'ar' => ['meta_title' => 'مكررنا ONØCRD', 'meta_desc' => 'معلومات تقنية ووصول EchoLink لمكرر ONØCRD.', 'title' => 'مكررنا', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'نعم / نعم (ترميز/فك)', 'callsign' => 'نداء', 'channel' => 'قناة', 'mode' => 'الوضع', 'mode_value' => 'وضع مكرر FM + EchoLink', 'input' => 'تردد الإدخال ( TX )', 'output' => 'تردد الإخراج ( RX )', 'shift' => 'الإزاحة', 'subtone' => 'نغمة CTCSS الفرعية', 'polarization' => 'الاستقطاب', 'polarization_value' => 'عمودي 6,5 dBi', 'locator' => 'المحدد', 'locator_value' => 'JO20LI', 'location' => 'الموقع', 'location_value' => 'Yvoir (Durnal)', 'power' => 'القدرة', 'power_value' => '25 W', 'altitude' => 'الارتفاع', 'altitude_value' => '314 m', 'tx' => 'إدخال ( TX )', 'rx' => 'إخراج ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'تم توفير وصول Echolink للأصدقاء خارج تغطية مكرر Durnal.', 'p2' => 'يرجى تفضيل VHF إذا كنت ضمن تغطية المكرر. منارة صوتية كل 15 دقيقة.', 'p3' => 'المكرر SVXlink المثبت هو ربط SVXLink (Echolink) مع مكرر FM موجود. هنا: ONØCRD – Sysop ON4DL – نائب ON5GB.', 'p4' => 'بالتعاون مع ON4LS، أصبح الوصول إلى Echolink على ONØCRD متاحًا منذ 18/03/2021.'],
    'bn' => ['meta_title' => 'আমাদের ONØCRD রিপিটার', 'meta_desc' => 'ONØCRD রিপিটারের প্রযুক্তিগত তথ্য এবং EchoLink প্রবেশাধিকার।', 'title' => 'আমাদের রিপিটার', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'হ্যাঁ / হ্যাঁ (enc./dec.)', 'callsign' => 'কলসাইন', 'channel' => 'চ্যানেল', 'mode' => 'মোড', 'mode_value' => 'FM রিপিটার মোড + EchoLink', 'input' => 'ইনপুট ফ্রিকোয়েন্সি ( TX )', 'output' => 'আউটপুট ফ্রিকোয়েন্সি ( RX )', 'shift' => 'শিফট', 'subtone' => 'CTCSS সাবটোন', 'polarization' => 'পোলারাইজেশন', 'polarization_value' => 'উল্লম্ব 6,5 dBi', 'locator' => 'লোকেটর', 'locator_value' => 'JO20LI', 'location' => 'অবস্থান', 'location_value' => 'Yvoir (Durnal)', 'power' => 'ক্ষমতা', 'power_value' => '25 W', 'altitude' => 'উচ্চতা', 'altitude_value' => '314 m', 'tx' => 'ইনপুট ( TX )', 'rx' => 'আউটপুট ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'ডুরনাল রিপিটারের কভারেজের বাইরে থাকা বন্ধুদের জন্য Echolink অ্যাক্সেস উপলব্ধ।', 'p2' => 'কভারেজের মধ্যে থাকলে অনুগ্রহ করে VHF অগ্রাধিকার দিন। প্রতি ১৫ মিনিটে ভয়েস বিকন।', 'p3' => 'ইনস্টল করা SVXlink রিপিটারটি বিদ্যমান FM রিপিটারের সাথে একটি SVXLink (Echolink) লিংক। এখানে: ONØCRD – Sysop ON4DL – ডেপুটি ON5GB।', 'p4' => 'ON4LS-এর সহযোগিতায় 18/03/2021 থেকে ONØCRD-এ Echolink অ্যাক্সেস চালু রয়েছে।'],
    'hi' => ['meta_title' => 'हमारा ONØCRD रिपीटर', 'meta_desc' => 'ONØCRD रिपीटर के तकनीकी विवरण और EchoLink पहुँच।', 'title' => 'हमारा रिपीटर', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'हाँ / हाँ (enc./dec.)', 'callsign' => 'कॉलसाइन', 'channel' => 'चैनल', 'mode' => 'मोड', 'mode_value' => 'FM रिपीटर मोड + EchoLink', 'input' => 'इनपुट आवृत्ति ( TX )', 'output' => 'आउटपुट आवृत्ति ( RX )', 'shift' => 'शिफ्ट', 'subtone' => 'CTCSS सबटोन', 'polarization' => 'ध्रुवीकरण', 'polarization_value' => 'वर्टिकल 6,5 dBi', 'locator' => 'लोकेटर', 'locator_value' => 'JO20LI', 'location' => 'स्थान', 'location_value' => 'Yvoir (Durnal)', 'power' => 'शक्ति', 'power_value' => '25 W', 'altitude' => 'ऊँचाई', 'altitude_value' => '314 m', 'tx' => 'इनपुट ( TX )', 'rx' => 'आउटपुट ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'डुरनाल रिपीटर की पहुँच से बाहर मित्रों के लिए Echolink पहुँच उपलब्ध है।', 'p2' => 'यदि आप रिपीटर कवरेज में हैं तो कृपया VHF को प्राथमिकता दें। हर 15 मिनट में वॉइस बीकन।', 'p3' => 'स्थापित SVXlink रिपीटर मौजूदा FM रिपीटर के साथ SVXLink (Echolink) लिंक है। यहाँ: ONØCRD – Sysop ON4DL – डिप्टी ON5GB।', 'p4' => 'ON4LS के सहयोग से ONØCRD पर Echolink पहुँच 18/03/2021 से उपलब्ध है।'],
    'id' => ['meta_title' => 'Repeater ONØCRD kami', 'meta_desc' => 'Informasi teknis dan akses EchoLink untuk repeater ONØCRD.', 'title' => 'Repeater kami', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Ya / Ya (enc./dec.)', 'callsign' => 'Callsign', 'channel' => 'Kanal', 'mode' => 'Mode', 'mode_value' => 'Mode repeater FM + EchoLink', 'input' => 'Frekuensi input ( TX )', 'output' => 'Frekuensi output ( RX )', 'shift' => 'Shift', 'subtone' => 'Subtone CTCSS', 'polarization' => 'Polarisasi', 'polarization_value' => 'Vertikal 6,5 dBi', 'locator' => 'Locator', 'locator_value' => 'JO20LI', 'location' => 'Lokasi', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Daya', 'power_value' => '25 W', 'altitude' => 'Ketinggian', 'altitude_value' => '314 m', 'tx' => 'Input ( TX )', 'rx' => 'Output ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Akses Echolink tersedia untuk rekan di luar jangkauan repeater Durnal.', 'p2' => 'Harap utamakan VHF jika Anda berada dalam jangkauan repeater. Beacon suara setiap 15 menit.', 'p3' => 'Repeater SVXlink yang dipasang adalah tautan SVXLink (Echolink) dengan repeater FM yang ada. Di sini: ONØCRD – Sysop ON4DL – Wakil ON5GB.', 'p4' => 'Berkat kolaborasi dengan ON4LS, akses Echolink di ONØCRD tersedia sejak 18/03/2021.'],
    'ja' => ['meta_title' => '私たちのONØCRDレピーター', 'meta_desc' => 'ONØCRDレピーターの技術情報とEchoLinkアクセス。', 'title' => '私たちのレピーター', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'はい / はい (enc./dec.)', 'callsign' => 'コールサイン', 'channel' => 'チャンネル', 'mode' => 'モード', 'mode_value' => 'FMレピーターモード + EchoLink', 'input' => '入力周波数 ( TX )', 'output' => '出力周波数 ( RX )', 'shift' => 'シフト', 'subtone' => 'CTCSSサブトーン', 'polarization' => '偏波', 'polarization_value' => '垂直 6,5 dBi', 'locator' => 'ロケーター', 'locator_value' => 'JO20LI', 'location' => '場所', 'location_value' => 'Yvoir (Durnal)', 'power' => '出力', 'power_value' => '25 W', 'altitude' => '標高', 'altitude_value' => '314 m', 'tx' => '入力 ( TX )', 'rx' => '出力 ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Durnalレピーターの範囲外の仲間向けにEcholinkアクセスを提供しています。', 'p2' => 'レピーターの範囲内ではVHFを優先してください。15分ごとに音声ビーコンがあります。', 'p3' => '設置されたSVXlinkレピーターは既存のFMレピーターとSVXLink（Echolink）連携しています。ここでは: ONØCRD – Sysop ON4DL – 代理 ON5GB。', 'p4' => 'ON4LSの協力により、ONØCRDでのEcholinkアクセスは2021/03/18から利用可能です。'],
    'ru' => ['meta_title' => 'Наш репитер ONØCRD', 'meta_desc' => 'Техническая информация и доступ EchoLink для репитера ONØCRD.', 'title' => 'Наш репитер', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => 'Да / Да (enc./dec.)', 'callsign' => 'Позывной', 'channel' => 'Канал', 'mode' => 'Режим', 'mode_value' => 'Режим FM-репитера + EchoLink', 'input' => 'Входная частота ( TX )', 'output' => 'Выходная частота ( RX )', 'shift' => 'Сдвиг', 'subtone' => 'CTCSS-субтон', 'polarization' => 'Поляризация', 'polarization_value' => 'Вертикальная 6,5 dBi', 'locator' => 'Локатор', 'locator_value' => 'JO20LI', 'location' => 'Местоположение', 'location_value' => 'Yvoir (Durnal)', 'power' => 'Мощность', 'power_value' => '25 W', 'altitude' => 'Высота', 'altitude_value' => '314 m', 'tx' => 'Вход ( TX )', 'rx' => 'Выход ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => 'Доступ Echolink доступен друзьям вне зоны покрытия репитера Durnal.', 'p2' => 'Если вы в зоне покрытия репитера, пожалуйста, используйте VHF. Голосовой маяк каждые 15 минут.', 'p3' => 'Установленный репитер SVXlink — это связка SVXLink (Echolink) с существующим FM-репитером. Здесь: ONØCRD – Sysop ON4DL – Заместитель ON5GB.', 'p4' => 'Благодаря сотрудничеству с ON4LS, доступ Echolink на ONØCRD работает с 18/03/2021.'],
    'zh' => ['meta_title' => '我们的 ONØCRD 中继台', 'meta_desc' => 'ONØCRD 中继台的技术信息与 EchoLink 接入。', 'title' => '我们的中继台', 'callsign_value' => 'ONØCRD', 'channel_value' => 'RV 46', 'input_value' => '144,975', 'output_value' => '145,575', 'shift_value' => '0,6', 'subtone_value' => '131,8', 'subtone_status_value' => '是 / 是 (enc./dec.)', 'callsign' => '呼号', 'channel' => '信道', 'mode' => '模式', 'mode_value' => 'FM 中继模式 + EchoLink', 'input' => '输入频率 ( TX )', 'output' => '输出频率 ( RX )', 'shift' => '频移', 'subtone' => 'CTCSS 亚音', 'polarization' => '极化', 'polarization_value' => '垂直 6,5 dBi', 'locator' => '定位器', 'locator_value' => 'JO20LI', 'location' => '位置', 'location_value' => 'Yvoir (Durnal)', 'power' => '功率', 'power_value' => '25 W', 'altitude' => '海拔', 'altitude_value' => '314 m', 'tx' => '输入 ( TX )', 'rx' => '输出 ( RX )', 'unit_mhz' => 'MHz', 'unit_hz' => 'Hz', 'p1' => '为超出 Durnal 中继覆盖范围的朋友提供了 Echolink 接入。', 'p2' => '若在中继覆盖范围内，请优先使用 VHF。每 15 分钟有语音信标。', 'p3' => '已安装的 SVXlink 中继是与现有 FM 中继连接的 SVXLink（Echolink）实现。此处：ONØCRD – Sysop ON4DL – 代理 ON5GB。', 'p4' => '在 ON4LS 的协作下，ONØCRD 的 Echolink 接入自 18/03/2021 起可用。'],
];
$i18n = i18n_expand_supported_locales($i18n);
$t = static function (string $key) use ($locale, $i18n): string {
    return (string) (($i18n[$locale] ?? $i18n['fr'])[$key] ?? $key);
};

set_page_meta([
    'title' => $t('meta_title'),
    'description' => $t('meta_desc'),
    'schema_type' => 'WebPage',
]);

ob_start();
?>
<section class="card max-w-5xl mx-auto">
    <h1 class="text-3xl font-bold text-slate-900 text-center"><?= e($t('title')) ?></h1>
    <div class="mt-6 overflow-x-auto">
        <table class="w-full min-w-[720px] border border-slate-200 rounded-xl overflow-hidden text-sm">
            <tbody>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('callsign')) ?></th><td class="px-4 py-3"><?= e($t('callsign_value')) ?></td><td class="px-4 py-3"><?= e($t('tx')) ?></td><td class="px-4 py-3"><?= e($t('rx')) ?></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('channel')) ?></th><td class="px-4 py-3"><?= e($t('channel_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('mode')) ?></th><td class="px-4 py-3"><?= e($t('mode_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('input')) ?></th><td class="px-4 py-3"><?= e($t('input_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_mhz')) ?></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('output')) ?></th><td class="px-4 py-3"><?= e($t('output_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_mhz')) ?></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('shift')) ?></th><td class="px-4 py-3"><?= e($t('shift_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_mhz')) ?></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('subtone')) ?></th><td class="px-4 py-3"><?= e($t('subtone_value')) ?></td><td class="px-4 py-3"><?= e($t('unit_hz')) ?></td><td class="px-4 py-3"><?= e($t('subtone_status_value')) ?></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('polarization')) ?></th><td class="px-4 py-3"><?= e($t('polarization_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('locator')) ?></th><td class="px-4 py-3"><?= e($t('locator_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('location')) ?></th><td class="px-4 py-3"><?= e($t('location_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr class="border-b border-slate-200"><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('power')) ?></th><td class="px-4 py-3"><?= e($t('power_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            <tr><th scope="row" class="bg-slate-50 px-4 py-3 text-left font-semibold text-slate-800"><?= e($t('altitude')) ?></th><td class="px-4 py-3"><?= e($t('altitude_value')) ?></td><td class="px-4 py-3"></td><td class="px-4 py-3"></td></tr>
            </tbody>
        </table>
    </div>

    <div class="mt-6 space-y-4 text-slate-700">
        <p><?= e($t('p1')) ?></p>
        <p><?= e($t('p2')) ?></p>
        <p><?= e($t('p3')) ?></p>
        <p><?= e($t('p4')) ?></p>
    </div>
</section>
<?php
echo render_layout((string) ob_get_clean(), $t('title'));
