name: Compress Images

on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Dossier à compresser"
        required: true
        default: "assets/img"

  pull_request:
    paths:
      - "assets/img/**/*.jpg"
      - "assets/img/**/*.jpeg"
      - "assets/img/**/*.png"
      - "assets/img/**/*.webp"

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
